CHANGELOG.md, package-lock.json, package.json, readme.md, src/LanguageServer.spec.ts, src/LanguageServer.ts, src/ProgramBuilder.spec.ts, src/util.ts
Fixed race condition in languageserver that was killing the server when sending diagnostics too early.
=> Fix languageserver race condition

src/parser/parser/Parser.ts, src/parser/parser/tests/controlFlow/If.spec.ts
Fixed syntax issues related to single-line if statements. 
Thanks @lvcabral for the fix in upstream brs. (https://github.com/sjbarag/brs/pull/330)
Related: [brs#252](https://github.com/sjbarag/brs/issues/252), [brs#253](https://github.com/sjbarag/brs/issues/253),  [brs#309](https://github.com/sjbarag/brs/issues/309).
=> Fix issue with single-line if statements.

.gitignore, package-lock.json, src/LanguageServer.ts, src/Program.ts, src/files/BrsFile.spec.ts, src/files/BrsFile.ts
This addresses some errors with reading tokens on hovers and also addresses some files not being detected in the project correctly on open.
=> Fix race condition between project run and opened files

src/ProgramBuilder.spec.ts, src/ProgramBuilder.ts
Do this so running from the command line will recognize that linting failed
=> Throw an error when running once

.gitignore, .vscode/launch.json, benchmarks/Benchmarker.ts, package-lock.json, package.json, src/Cache.spec.ts, src/Cache.ts, src/DependencyGraph.spec.ts, src/DependencyGraph.ts, src/FunctionScope.spec.ts, src/Logger.ts, src/Program.spec.ts, src/Program.ts, src/ProgramBuilder.spec.ts, src/ProgramBuilder.ts, src/Scope.spec.ts, src/Scope.ts, src/XmlScope.spec.ts, src/XmlScope.ts, src/files/BrsFile.Class.spec.ts, src/files/BrsFile.spec.ts, src/files/BrsFile.ts, src/files/XmlFile.spec.ts, src/files/XmlFile.ts, src/globalCallables.ts, src/validators/ClassValidator.ts, tsconfig.json
There were many bugs related to import statements not working properly.
This PR redesigns the entire event flow so that changes flow in a single direction. As files are added, they update their dependency list. The dependencyGraph then notifies all other files that are dependent on that file, so only the minimal amount of files need to be re-validated when a file is changed. This redesign also improves performance because in the previous model, every single component would be notified of every single file change.
=> Fix imports

src/files/BrsFile.spec.ts, src/parser/Statement.ts, src/util.spec.ts
=> Fix transpile for empty conditional blocks.

src/LanguageServer.ts, src/TaskThrottle.spec.ts, src/TaskThrottler.ts
Decoupled validation from file-change handling, allowing to throttle validations.
Fixes #142
=> Fix: prevent accumulating multiple validations

package-lock.json, package.json, src/cli.ts
Fixes #167 - bugs in cli that wouldn't properly read bsconfig values.
Fixes #168 - bug in cli that doesn't use `retain-staging-folder` argument properly.
=> Fix cli overrides

src/files/BrsFile.ts
Some fields are really needed only when we actively use code completion on one file so it should be computed on demand. 
This cuts up to 30% parsing time.
=> Not all the BrsFile fields need to be filled at parse time

src/parser/Parser.ts
Micro optimisation of hot parser functions - seems about 10% faster parse.
=> Performance: parser micro-optimisation

src/LanguageServer.ts, src/Throttler.ts
Make it more responsive!
Tested in a 480+ brs files project.
=> Now that validation is fast, reduce timings

CHANGELOG.md, src/DiagnosticMessages.ts, src/files/XmlFile.spec.ts, src/files/XmlFile.ts
- Remove bs1106 because it's not helpful.
- Support single quote script tags
=> Support xml singlequotes

docs/classes.md, src/Program.spec.ts, src/files/BrsFile.spec.ts, src/parser/Statement.ts, src/validators/ClassValidator.ts
Fixes issues generating class typedefs.
=> Typedef fixes

src/astUtils/reflection.ts, src/astUtils/stackedVisitor.ts, src/astUtils/visitors.ts
When writing a TS plugin with null safety enabled, the visitor API needs adjustements.
=> Make utils compatible with TS strict null check (in plugins)

.eslintrc.js, bsconfig.schema.json, src/BsConfig.ts, src/Program.spec.ts, src/cli.ts, src/files/BrsFile.spec.ts, src/files/BrsFile.ts, src/util.ts
- add config option to enable/disable emitting source maps
- disable source map generation by default. (this is a breaking change, but we're still in 0.* version land, so we can do what we want!!!)
=> Sourcemaps off by default, add config to enable

src/files/BrsFile.Class.spec.ts, src/parser/Statement.ts
=> Fix grandchild class super index bug.

src/DiagnosticMessages.ts, src/Scope.spec.ts, src/Scope.ts, src/astUtils/reflection.ts, src/lexer/TokenKind.ts, src/parser/Expression.ts, src/parser/Parser.Class.spec.ts, src/parser/Parser.spec.ts, src/parser/Parser.ts, src/parser/Statement.ts, src/types/ArrayType.ts, src/types/BooleanType.ts, src/types/BscType.ts, src/types/CustomType.ts, src/types/DoubleType.ts, src/types/DynamicType.ts, src/types/FloatType.ts, src/types/FunctionType.ts, src/types/IntegerType.ts, src/types/InterfaceType.ts, src/types/InvalidType.ts, src/types/LongIntegerType.ts, src/types/ObjectType.ts, src/types/StringType.ts, src/types/UninitializedType.ts, src/types/VoidType.ts, src/util.ts, src/validators/ClassValidator.ts
I don't think this works yet "inside" a namespace...
=> Allows "as <CustomType>" in parameter and return type declarations

src/LanguageServer.ts, src/Program.spec.ts, src/Program.ts, src/Scope.ts, src/astUtils/reflection.ts, src/files/BrsFile.ts, src/parser/Expression.ts, src/parser/Parser.ts, src/parser/Statement.ts, src/util.spec.ts, src/util.ts
Enhances intellisense, definitions and signature behaviour. In doing so, also normalizes the getSignature LSP function to pass responsiblites to program, using file and position. Refactorings include removing pre-AST functions for signature and adding ASTObject<T> to provide file context for statements, which saves expensive lookups later on. Fixes go to definition and signatures for namespace functions, classes, and callfunc calls.
*Known issues: *
**completions: **
- I appear to be getting too many classes back for new keyword completions - this was scoped to files in scope before, and has since gone awry.. 
- Would be lovely to prioritize completions somehow, so that property values (generic case) move below m. and class member completions
-  Appear to be getting namespaces that are …
=> Function signature and intellisense improvements

src/Program.ts, src/Scope.ts, src/files/BrsFile.Class.spec.ts, src/files/BrsFile.spec.ts, src/files/BrsFile.ts, src/parser/Expression.ts, src/parser/Statement.ts
Fixes bug with class inheritance during transpile that wasn't properly handling relative class names in a namespace.
=> Fix global superclass index

.vscode/launch.json, docs/annotations.md, scripts/compile-doc-examples.ts, src/parser/TranspileState.ts
Just a few small tweaks to the project.
- add launch config for debugging the docs transpiler script
- update the docs transpiler to support multiple bsconfig values
- add updated annotations transpiled doc code blocks
=> Misc updates

src/parser/Expression.ts, src/parser/Parser.spec.ts
=> adds support for negative numbers in annotation args

src/LanguageServer.ts, src/files/BrsFile.ts
Found another situation that causes the language server to show errors.
=> Fix validate crash

src/files/XmlFile.spec.ts, src/parser/SGTypes.ts
I found that if you remove one attribute, it removes all.
=> fixes attributes being wrongly removed

src/astUtils/visitors.spec.ts, src/astUtils/visitors.ts, src/files/BrsFile.Class.spec.ts, src/parser/Statement.ts
=> fixes super.methodCall() not transpiling in all cases

src/Program.spec.ts, src/Program.ts
Fixes #307 (no signatures for function call with zero leading characters).
=> Fix signature bug

src/Program.spec.ts, src/files/BrsFile.spec.ts, src/parser/Expression.ts, src/parser/Statement.ts
- include annotations in type definition output
=> include annotations in type files

src/DiagnosticFilterer.spec.ts, src/DiagnosticFilterer.ts
Fixes performance issue when filtering diagnostics for projects with a high diagnostic count. This will have a very minor performance boost for all projects.
I recently opened a project with over 100k diagnostics (all being hidden by diagnostic filters), and the performance was terrible. It took 49 seconds to filter all of the diagnostics. After this fix, it only took 227milliseconds. 
The gist of the issue is that the DiagnosticFilterer class was doing something like this (pseudocode):
```typescript
for(var filter of diagnosticFilters) {
for(var filePath in diagnostics.map(x=> x.filePath)) {
for(var diagnostic of diagnosticsByFilePath[filePath]){
filterDiagnosticIfMatch(filter, diagnostic);
}
}
}
```
Notice the problem here? We were not creating a distinct list of file paths, but rather …
=> Fix performance bug in DiagnosticFilterer

src/Scope.ts
=> Don't crash on null relativePath

src/Logger.ts, src/PluginInterface.spec.ts, src/PluginInterface.ts, src/Program.spec.ts, src/Program.ts, src/ProgramBuilder.ts, src/Scope.spec.ts, src/Scope.ts, src/files/BrsFile.spec.ts
Small tweaks to the logging system to help make `info`  less verbose.
=> tweaks to the logging system.

src/Program.spec.ts, src/Program.ts
Fixes a language server crash for completions next to a callfunc. 
Fixes #352
=> Safer completion handling for callfuncs.

src/Program.spec.ts, src/Program.ts, src/files/BrsFile.ts, src/parser/Parser.ts
Move all of the token-specific functions out of `BrsFile.ts` and into `Parser.ts`
=> Move token-specific functions into `Parser.ts`

src/CodeActionUtil.ts
Also add missing information in the action.
=> Fix code actions construction for "replace" tasks

src/Logger.spec.ts, src/Logger.ts, src/Stopwatch.spec.ts
Added some unit tests for the `Logger` and `Stopwatch` classes.
=> Add unit tests for Logger and Stopwatch

src/globalCallables.spec.ts, src/globalCallables.ts
=> Adds a bunch of functions from v30/bslCore library to the global callables list

src/ProgramBuilder.ts
=> CLI outputs the path of bsconfig.json on startup

src/files/BrsFile.Class.spec.ts, src/parser/Expression.ts, src/validators/ClassValidator.ts
Fixes #460 (when child class field has same name as parent class method).
=> Fix crash with mismatched class members

src/Scope.ts, src/globalCallables.spec.ts, src/globalCallables.ts, src/interfaces.ts
Fixes a bug in our global function parameter checking that was not properly enforcing optional/required status for parameters.
=> Set isOptional value on every global func param

src/files/BrsFile.spec.ts, src/files/BrsFile.ts
Fixes bug that crashes the hover anytime you hover over a global function.
=> Fix crash when hovering over global functions.

docs/plugins.md, src/Scope.spec.ts, src/Scope.ts, src/interfaces.ts
Adds `onScopeValidate` plugin event.
=> Add `onScopeValidate` plugin event.

src/Cache.spec.ts, src/Cache.ts
For the Cache class, instead of maintaining a separate internal map, we now just extend map.
=> Cache extends `Map`.

bsconfig.schema.json
Add missing `require` entry to the bsconfig.schema.json so we get intellisense in vscode and other tools.
=> Add the `require` entry to the bsconfig.schema.json

src/Program.ts, src/preprocessor/Manifest.spec.ts, src/preprocessor/Manifest.ts, src/testHelpers.spec.ts, src/types/InterfaceType.spec.ts
Makes manifest parsing more accurate. Re-enable and fix manifest tests.
=> Fix manifest issues

src/Cache.ts, src/files/BrsFile.ts, src/testHelpers.spec.ts
Adds better type tracking for when the cache is used for multiple types.
=> More flexible cache typing

.eslintrc.js, .github/workflows/build.yml, package.json, scripts/test-related-projects.ts, scripts/tsconfig.json
Runs tests against some known public bsc plugins to help us detect when changes might break plugins.
=> Adds tests for known bsc plugins

src/astUtils/AstEditor.spec.ts, src/astUtils/AstEditor.ts
Add array `shift`, `unshift`, `push`, `pop` methods to AstEditor
=> Add more ast editor functions

src/astUtils/AstEditor.spec.ts, src/astUtils/AstEditor.ts, src/files/BrsFile.Class.spec.ts, src/files/BrsFile.ts, src/parser/BrsTranspileState.ts, src/parser/Statement.ts
Fix class statement transpile bug that was modifying AST on first transpile, and then causing issues for future transpiles when in watch mode.
=> Better super handling

src/LanguageServer.spec.ts
Use array brackets for LanguageServer.spec.ts and a typed variable instead of an `any` type, provides better type tracking.
=> Use index accessor for lang server tests

src/Scope.ts, src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts, src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts, src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts, src/bscPlugin/validation/ScopeValidator.ts, src/interfaces.ts, src/parser/tests/statement/Enum.spec.ts, src/util.ts
Adds much better syntax highlighting (via semantic tokens) for enums, classes, and namespaces.
**Before:**
**After:**
=> Better enum/class/namespace semantic tokens

src/parser/tests/statement/Enum.spec.ts
Adds a test verifying that enums transpile within more complicated if statements.
=> Test for enum transpiling inside if statements

src/files/BrsFile.Class.spec.ts, src/parser/Statement.ts
Fixes a bug in class transpiling that was permanently modifying classes instead of using the AstEditor.
=> fix bug with class transpile in watch mode

src/Program.spec.ts, src/Program.ts, src/Scope.ts, src/bscPlugin/validation/ScopeValidator.ts, src/files/BrsFile.ts, src/parser/tests/statement/Enum.spec.ts, src/util.ts, src/validators/ClassValidator.ts
VSCode's `Location.create()` is slow (they probably do more validation under the hood. We care about raw speed, so use a faster util function. Similar to the `util.createRange()` and `util.createPosition()` functions introduced some time ago.
=> Use `util.createLocation`, not `Location.create()`

docs/constants.md, src/Program.ts, src/Scope.ts, src/astUtils/reflection.ts, src/astUtils/visitors.ts, src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts, src/bscPlugin/validation/BrsFileValidator.ts, src/bscPlugin/validation/ScopeValidator.ts, src/files/BrsFile.ts, src/lexer/Lexer.spec.ts, src/lexer/TokenKind.ts, src/parser/Parser.Class.spec.ts, src/parser/Parser.ts, src/parser/Statement.ts, src/parser/tests/statement/ConstStatement.spec.ts, src/parser/tests/statement/Enum.spec.ts, src/util.ts
Adds support for defining compile-time constants. These are replaced at usage locations at runtime, and work very similarly to enums.
=> New Language Feature: Constants

src/LanguageServer.ts, src/bscPlugin/hover/HoverProcessor.spec.ts, src/bscPlugin/hover/HoverProcessor.ts, src/files/BrsFile.ts
Adds hover support for `const` references.
=> Add hover for CONST references.

src/files/BrsFile.spec.ts, src/preprocessor/Manifest.ts, src/preprocessor/Preprocessor.ts
=> Fix case sensitivity issue with bs_const values

docs/classes.md
Add section to class docs explaining how function instance binding works.
=> Add class method binding docs

src/bscPlugin/validation/BrsFileValidator.ts, src/parser/Statement.ts, src/parser/tests/statement/Enum.spec.ts
=> Fix enum error for negative values

src/Scope.spec.ts, src/Scope.ts, src/files/BrsFile.spec.ts
Fixes a crash in getDefinition.
=> Fix crash in `getDefinition`

src/PluginInterface.spec.ts, src/PluginInterface.ts, src/Program.spec.ts, src/Program.ts, src/ProgramBuilder.ts, src/Scope.spec.ts, src/bscPlugin/validation/BrsFileValidator.ts, src/files/BrsFile.spec.ts, src/parser/tests/statement/Continue.spec.ts
Fixes a crash when validating continue statements that don't have the loop type after them. 
Fixes #751
=> Fix exception while validating continue statement

src/parser/Expression.ts, src/parser/Statement.ts
Uses `util.createBoundingRange()` for all of the internal AST range calculations, which eliminates a lot of verbose ternary null coalescing code.
=> Simplify the ast range logic

.gitignore, benchmarks/index.ts, benchmarks/package-lock.json, benchmarks/package.json, benchmarks/target-runner.js
Adds ability to generate .cpuprofile files when running benchmarks.
=> Add cpuprofile ability to the benchmarks

README.md
Fix lint error code for diagnosticSeverityOverrides
=> Fix lint error code for diagnosticSeverityOverrides

src/Program.ts, src/Scope.spec.ts, src/SymbolTable.spec.ts, src/SymbolTable.ts, src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts, src/bscPlugin/validation/BrsFileValidator.ts, src/bscPlugin/validation/ScopeValidator.ts, src/files/BrsFile.ts, src/globalCallables.ts, src/interfaces.ts, src/parser/Expression.ts, src/parser/Parser.Class.spec.ts, src/parser/Parser.spec.ts, src/parser/Statement.ts, src/parser/tests/expression/TypeExpression.spec.ts, src/types/BscType.ts, src/types/ClassType.spec.ts, src/types/InheritableType.ts, src/types/InterfaceType.spec.ts, src/types/InterfaceType.ts, src/types/ObjectType.ts, src/types/ReferenceType.spec.ts, src/types/ReferenceType.ts, src/types/UnionType.spec.ts, src/types/helper.spec.ts, src/util.spec.ts, src/validators/ClassValidator.ts
Rename enum `SymbolTypeFlags` to `SymbolTypeFlag`
=> Rename SymbolTypeFlags to SymbolTypeFlag

src/LanguageServer.spec.ts, src/PluginInterface.spec.ts, src/Program.spec.ts, src/Program.ts, src/ProgramBuilder.ts, src/Scope.spec.ts, src/Scope.ts, src/astUtils/visitors.spec.ts, src/bscPlugin/BscPlugin.ts, src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts, src/bscPlugin/validation/ProgramValidator.ts, src/files/BrsFile.spec.ts, src/files/XmlFile.spec.ts, src/interfaces.ts
Converts all plugin event parameters to be a single event object rather than ordered parameters.
=> Convert plugin params to single event object

src/LanguageServer.ts, src/Logger.ts, src/ProgramBuilder.ts
Adds a numeric index to each language server program so we can distinguish between the logs as to which program the log netry corresponds to
=> Add project index to language server log entries

src/interfaces.ts
Follow up to #844 (oops)
Thanks!
=> Expose event interface

src/util.spec.ts, src/util.ts
Fixes a crash in utils when comparing ranges when the range or position is undefined
=> Fix crashes in util for null ranges

src/DiagnosticMessages.ts, src/bscPlugin/validation/ScopeValidator.spec.ts, src/bscPlugin/validation/ScopeValidator.ts
=> Validates DottedSetStatements for type compatibility

src/DiagnosticMessages.ts, src/astUtils/reflection.ts, src/bscPlugin/validation/ScopeValidator.spec.ts, src/bscPlugin/validation/ScopeValidator.ts, src/globalCallables.ts, src/parser/Statement.ts, src/parser/tests/statement/ConstStatement.spec.ts, src/util.ts
=> Adds validation for binary operators

docs/interfaces.md, src/Scope.spec.ts, src/parser/Parser.ts, src/parser/tests/statement/InterfaceStatement.spec.ts
Adds support for defining method parameters on interfaces.
=> Interface param support

src/bscPlugin/validation/ScopeValidator.spec.ts, src/types/DoubleType.ts, src/types/FloatType.ts, src/types/IntegerType.ts, src/types/LongIntegerType.ts, src/types/StringType.ts, src/types/UnionType.ts, src/types/helper.spec.ts, src/types/helpers.ts
For primitive types, allows returning a compatible enum member.
Fixes #903
=> Fixes Enum return validation

src/deferred.ts
Fix the `reject()` typing for the `Deferred` class.
=> Better typing for `Deferred`

.github/workflows/create-package.yml
Adds support for adding `create-package` labels to pull requests, at which point github actions will auto-build a temporary .tgz npm package.
=> Add create-package label build script

src/types/BuiltInInterfaceAdder.spec.ts, src/types/BuiltInInterfaceAdder.ts
=> Classes do not include AA members

src/SymbolTable.ts, src/bscPlugin/completions/CompletionsProcessor.spec.ts, src/bscPlugin/completions/CompletionsProcessor.ts, src/bscPlugin/validation/BrsFileValidator.ts
=> Remove post-transpiled symbols from .bs code completion

src/Program.ts, src/Scope.ts, src/XmlScope.spec.ts, src/XmlScope.ts, src/bscPlugin/BscPlugin.ts, src/bscPlugin/definition/DefinitionProvider.spec.ts, src/bscPlugin/definition/DefinitionProvider.ts, src/files/BrsFile.ts, src/interfaces.ts
Allow plugins to contribute to `go to definition` results in the language server
=> Add plugin hooks for getDefinition

README.md
=> Fix maestro link on readme

src/bscPlugin/validation/ScopeValidator.spec.ts, src/bscPlugin/validation/ScopeValidator.ts, src/interfaces.ts, src/parser/Expression.ts, src/parser/Statement.ts, src/types/InheritableType.ts, src/util.spec.ts
=> Adds validation when trying to access a class member directly on a class name

src/bscPlugin/hover/HoverProcessor.spec.ts, src/bscPlugin/hover/HoverProcessor.ts, src/lexer/TokenKind.ts, src/parser/Parser.ts, src/parser/Statement.ts
=> Adds type to const hovers and adds hover for for-each loop vars

src/Scope.spec.ts, src/bscPlugin/validation/BrsFileValidator.ts
- Types 'm' as AssocArray in function in AALiteral
Fixes #1084
=> Types 'm' as AssocArray in function in AALiteral

src/PluginInterface.ts, src/Scope.ts, src/XmlScope.ts, src/bscPlugin/validation/ScopeValidator.ts
Move the `scope.validate()` call into the BscPlugin
=> Move scope.validate() into BscPlugin

src/Scope.spec.ts, src/util.spec.ts, src/util.ts
=> Fixes bitwise operator typing

.github/workflows/build.yml
Fix bug with node14 on macos-latest arm64
=> Fix node14 issues

.github/workflows/build.yml
Fix bug with node14 on macos-latest arm64
=> Fix node14 bug on mac

src/bscPlugin/completions/CompletionsProcessor.spec.ts, src/bscPlugin/validation/BrsFileValidator.ts, src/bscPlugin/validation/ScopeValidator.spec.ts, src/parser/Expression.ts
=> Fixes issue with default params referencing previous ones

package-lock.json, package.json, src/logging.ts
Fix output formatting with the new logger updates so it matches what was in the previous logger.
=> Fix formatting with logger output

src/bscPlugin/completions/CompletionsProcessor.spec.ts, src/bscPlugin/completions/CompletionsProcessor.ts, src/bscPlugin/hover/HoverProcessor.spec.ts, src/bscPlugin/hover/HoverProcessor.ts
Fix several crashes in the language server related to missing range or AST properties.
=> Fix several lsp crashes for v1

src/bscPlugin/validation/ScopeValidator.ts, src/files/BrsFile.Class.spec.ts, src/files/BrsFile.spec.ts, src/interfaces.ts, src/parser/Expression.ts, src/parser/Statement.ts, src/util.spec.ts
Also:
- made TypeChainEntry.range optional
- fixed some tests
=> Removed TypeChainEntry.kind

src/bscPlugin/validation/ScopeValidator.spec.ts, src/bscPlugin/validation/ScopeValidator.ts
=> Allows numbers to be passed to a function that takes a bool

scripts/scrape-roku-docs.ts, src/Program.spec.ts, src/roku-types/data.json, src/util.ts
=> Adds messagePort methods to `ifSocketAsync` and `MultiStyleLabel.drawingStyles`

.eslintrc.js, package-lock.json, package.json
Prevent using devDependencies in prod code.
=> Flag using devDependency in production code

src/util.ts
Fix crash during transpile when a file was not associated with any scopes
=> Fix crash with missing scope

package-lock.json, src/index.ts
Export `Location` so it can be used directly in plugins
Also, ran `npm audit fix`
=> Convenience export Location

scripts/scrape-roku-docs.ts, src/roku-types/data.json
Addresses #1249 
I also found an issue with `ifArraySlice` that is fixed here.
The problem with ifArraySlice is that the docs were not parsed correctly -- instead of messing with the parsing, I just added it an an override.
This is how it looks on the Roku docs site - I think the double square brackets are the issue:
=> Fixes ifSystemLog and ifArraySlice docs

src/DiagnosticMessages.ts, src/Scope.spec.ts, src/bscPlugin/hover/HoverProcessor.spec.ts, src/bscPlugin/validation/ScopeValidator.ts, src/files/BrsFile.spec.ts, src/files/BrsFile.ts
=> Allow variables and parameters to shadow namespaces

src/parser/Expression.ts, src/parser/Statement.ts
=> Eliminate FunctionExpression.functionStatement

scripts/scrape-roku-docs.ts, src/Scope.spec.ts, src/roku-types/data.json
Fixes bug for missing known datatype `roIntrinsicDouble`.
=> Add support for roIntrinsicDouble

scripts/scrape-roku-docs.ts, src/roku-types/data.json
Scraper was not finding fields tables with 
` field | type | default | description `
I also re-scraped the docs, so there was a lot of new RokuOS 14 stuff...
=> Fixed an issue with doc scraper and re-scraped docs

src/bscPlugin/hover/HoverProcessor.spec.ts, src/parser/Expression.ts
=> Fixes type chain for looking up params with type defs from @param

src/DiagnosticMessages.ts, src/bscPlugin/validation/ScopeValidator.spec.ts, src/bscPlugin/validation/XmlFileValidator.ts, src/files/XmlFile.spec.ts, src/lexer/Lexer.ts, src/parser/Parser.spec.ts
Addresses #1372
Addresses #1329
=> Eliminates unnecessary import and fractional hex diagnostics

src/bscPlugin/validation/ScopeValidator.spec.ts
Addresses #1366
There were already a few unit tests for this, but I added a couple more
=> Added more unit tests for namespace as variable

src/bscPlugin/validation/ScopeValidator.spec.ts, src/parser/Expression.ts
=> Recognize literal strings as Associative Array members

src/Program.ts
Removes some temporary code that was accidentally committed to the project.
Discovered by @iBicha https://github.com/rokucommunity/brighterscript/pull/993#pullrequestreview-2688746483
=> Remove temporary code that was accidentally committed

CHANGELOG.md, src/parser/Expression.ts, src/parser/tests/expression/TemplateStringExpression.spec.ts
This includes the ternary transpile fix.
=> Merge master (e8dca23) into v1

src/astUtils/CachedLookups.ts, src/files/BrsFile.spec.ts, src/files/BrsFile.ts, src/util.spec.ts, src/util.ts
Fixes #1451
The issue is that a namespace search didn't take into account nested namespaces.
=> Fixes transpilation bug with enums and nested namespaces

CHANGELOG.md, src/bscPlugin/hover/HoverProcessor.spec.ts, src/globalCallables.ts
@TwitchBronBron I think this worked correctly?
=> Merge master@2b6cc17a into Release-v1

src/bscPlugin/validation/ScopeValidator.spec.ts, src/bscPlugin/validation/ScopeValidator.ts
=> Do not validate typedef files for return type mismatch

src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts, src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
=> Do not provide semantic tokens for primitive types

src/files/BrsFile.spec.ts, src/parser/Expression.ts
relates to bug report https://github.com/rokucommunity/brighterscript/issues/1413
=> Fix `removeParameterTypes` compile errors for return types

src/lsp/ProjectManager.spec.ts, src/lsp/ProjectManager.ts
Dedupe the hover results. 
**Before:**
**After:**
=> Dedupe hover results

.github/copilot-instructions.md, .github/workflows/copilot-setup-steps.yml
Adds a copilot-setup-steps.yml file to speed up interactions with copilot. Also adds custom instructions to help guide copilot towards better PRs.
=> chore: Add copilot files
