rokucommunity/brighterscript

- src/Program.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/parser/Parser.spec.ts
- src/parser/parser/Parser.ts
> Allow comments as their own lines in AA literals.

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/Program.spec.ts
- src/Program.ts
- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/util.spec.ts
- src/util.ts
This enhances the LanguageServer so that it supports basic file parsing and syntax checking regardless of whether you have a bsconfig.json file created or not. It will only parse "open" files, and once the files are closed their diagnostics are removed.
> Parse open files as standalone if not included in project.

- src/lexer/Lexer.ts
Certain tokens are used more than others in BrightScript. Since the lexer uses a switch statement on a per-char basis, it makes sense to optimize the lexer to look for the most common characters first. This PR optimizes the lexer based on the following test results. The test scanned every token across 20 different github projects to find the most commonly used tokens, and then sorted them by most-found to least-found. 
```
[ { kind: 'Identifier', count: 222360, percentage: 27.525 },
{ kind: 'Newline', count: 144800, percentage: 17.924 },
{ kind: 'Dot', count: 67827, percentage: 8.396 },
{ kind: 'RightParen', count: 48556, percentage: 6.011 },
{ kind: 'LeftParen', count: 48556, percentage: 6.011 },
{ kind: 'Equal', count: 41259, percentage: 5.107 },
{ kind: 'StringLiteral', count: 27127, …
```
> Reorder lexer switch statement for perf boost.

- src/Program.ts
Code was using the initial `options` instead of the prepared object.
Fixes #129
> Fix copy of output when `stagingFolderPath` isn't specified.

- README.md
- bsconfig.schema.json
- src/BsConfig.ts
- src/Program.spec.ts
- src/cli.ts
- src/files/BrsFile.ts
- src/parser/TranspileState.ts
- src/util.ts
Support for the `sourceRoot` property. This allows developers to copy their files to a staging area, and then run the BrighterScript compiler on the code, but have the source maps point to the original file location (instead of the staging location). 
Similar to the [--sourceRoot](https://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler flag in typescript
> Source root

- src/Program.spec.ts
- src/Scope.ts
When an `import` is redundant (e.g. component and parent import the same script) the compile produces "override" hints (BS1010) pointing to the same file, which are just noise while the important information is the redundant import warning.
Fixes #113
> Silence invalid "override" hints

- README.md
- bsconfig.schema.json
- docs/index.md
- docs/source-literals.md
- package-lock.json
- package.json
- src/BsConfig.ts
- src/files/BrsFile.spec.ts
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/TokenKind.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/tests/expression/SourceLiteralExpression.spec.ts
This PR adds several brighterscript-only source literals that get replaced at transpile-time. 
- source_file_path
- source_line_num
- function_name
- source_function_name
- source_location
- pkg_path
- pkg_location
Resolves #13
> Source literals

- src/DiagnosticMessages.ts
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/TokenKind.ts
- src/parser/Parser.ts
Added this so I can fix the formatter; it's more correct, as well, as we discussed.
> Adds begin and end template string literal tokens, so we can better format and understand the code down stream.

- README.md
- bsconfig.schema.json
- src/BsConfig.ts
- src/util.spec.ts
- src/util.ts
Adds ability to specify that a config path (via `extends` or `project`) is optional, so the parser should not fail if the file is not found.
Fixes #171
> Support optional `project` and `extends` props

- CHANGELOG.md
- src/DiagnosticMessages.ts
- src/LanguageServer.ts
- src/globalCallables.ts
- src/interfaces.ts
We incorrectly use the word "depricate" several places when it should be with an `e` "deprecate". This PR fixes that issue.
> Fix typo for deprecate

- src/DiagnosticMessages.ts
BS1104 and BS1105 are fairly critical issues and should be marked as errors instead of warnings.
Also, the wording is a bit off, so this fixes that.
> Upgrade BS1104 and BS1105 to DiagnosticSeverity.Error

- src/DiagnosticMessages.ts
- src/Program.spec.ts
- src/Program.ts
- src/files/XmlFile.ts
Detect when there are multiple components with the same name, and flag each occurrence as an error.
Resolves #185
> Detect and flag duplicate component names.

- src/LanguageServer.ts
- src/Program.ts
- src/Scope.ts
- src/XmlScope.ts
- src/astUtils/creators.ts
- src/brsTypes/Callable.ts
- src/files/BrsFile.ts
- src/files/XmlFile.ts
- src/globalCallables.ts
- src/lexer/Lexer.ts
- src/parser/ClassStatement.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/preprocessor/Chunk.ts
- src/util.ts
`vscode-languageserver`'s `Range.create()` seems to be significantly slower than creating the ranges manually. 
So, by switching the Lexer to use our own `createRange` function, we can improve its performance. With this change, scanning a 400 line file went from 746 ops/sec to 931 ops/sec
All benchmarks were performed against a 400 line brighterscript file. 
**Notable Changes:**
1. eliminate `Range.create()` in favor of `util.createRange()` and `util.createRangeFromPositions()`. 
- ~25% increase in `Lexer` performance
- ~12% increase in `Parser` performance
2. In `Lexer.ts`, don't return previous character in the `advance()` method.
- ~3% increase in `Lexer` performance
3. In `Lexer.ts`, replace switch statement with a static map.
- ~27% increase in `Lexer` performance
Overall, this has …
> Various performance tweaks

- src/util.ts
Currently, util.loadConfigFile uses `process.chdir`, which can run the risk of permanently changing `process.cwd` if the function fails. 
This PR addresses that concern by passing `cwd` in (and defaulting to `process.cwd()`), and utilizing that `cwd` parameter to resolve paths.
> Pass cwd instead of using process.chdir

- src/Program.ts
If the xml parse fails, we don't get a component name, which caused issues downstream and ultimately resulted in an annoying popup in the vscode interface. This should fix some of those issues.
> bugfix: don't crash if component is missing name

- src/astUtils/creators.ts
- src/astUtils/reflection.spec.ts
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/Token.ts
- src/parser/ClassStatement.ts
- src/parser/Parser.ts
- src/parser/tests/Parser.spec.ts
- src/parser/tests/statement/PrintStatement.spec.ts
- src/parser/tests/statement/Set.spec.ts
- src/util.ts
Adds `token.leadingWhitespace` which contains anywhitespace encountered between the previous token and the current token (excluding newlines which are their own token kind and would have `leadingWhitespace` of their own). At a later date, we will be deprecating emitting whitespace tokens from the Lexer in favor of this approach, but brighterscript-formatter current depends on those tokens so we will need to update that project first before deprecating. 
We also need this to support `ropm` in its prefixing efforts. `ropm` will use the parser, then prefix certain tokens, and then join everything back together as a single string. As the parser does not handle whitespace tokens properly, and it's inefficient to add logic to the parser to skip whitespace tokens, this seems like a better …
> Track leading whitespace on tokens.

- CHANGELOG.md
- src/Program.ts
- src/Scope.ts
- src/XmlScope.ts
- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/brsTypes/Callable.ts
- src/files/BrsFile.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/util.ts
- src/validators/ClassValidator.ts
A few minor AST tweaks:
- Remove usage of `instanceof` in favor of `is` functions from reflections.ts. This will help with plugin interoperability.
- rename `isEscapedCharCodeLiteral` to `isEscapedCharCodeLiteralExpression` to match other expression class names
- rename `FunctionParameter` to `FunctionParameterExpression` to match other expression class names
- convert `AAMemberExpression` interface into an expression class.
- convert `isBrsFile` and `isXmlFile` to check for constructor file name rather than file extension.
> AST improvements

- CHANGELOG.md
- src/diagnosticUtils.spec.ts
- src/diagnosticUtils.ts
Fixes issue where diagnostic printing fails critically whenever it encounters a diagnostic that has an invalid `Range`.
> Safer diagnostic printing

- docs/plugins.md
- src/Program.ts
- src/Scope.ts
- src/XmlScope.spec.ts
- src/XmlScope.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/examples/plugins/removePrint.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/interfaces.ts
- src/validators/ClassValidator.ts
- define new type called `BscFile` which is the union of `BrsFile` and `XmlFile` to simplify types across the project.
- Add generic type parameter for the "add file(s)" functions on `Program` to simplify code and tests.
> Add generic type param for addReplaceFile.

- src/files/BrsFile.spec.ts
- src/parser/Parser.ts
CallfuncExpression is NOT the same as a `CallExpression`, and therefore should not be included in the parser's `callExpressions` list. This PR fixes that issue.
Fixes #205
> Exclude CallfuncExpression from parser callExpression list

- src/DiagnosticCollection.spec.ts
- src/DiagnosticCollection.ts
- src/LanguageServer.ts
- src/brsTypes/Callable.ts
The original diagnostic functionality would send the entire list of diagnostics, for every file, after every validate. For a project with a large number of diagnostics, this causes extremely poor performance anytime the diagnostic window is open, because the VSCode diagnostic window re-renders every diagnostic since the references have all changed (since we sent new copies of everything).
This PR fixes that problem by only sending messages for files whose diagnostics have changed. If a file's diagnostics haven't changed since the last time they were sent, that file is skipped. Files with added/changed/removed diagnostics are the only ones that will be updated. 
VSCode handles diagnostics on a file-by-file basis, so by "skipping" a file when sending diagnostics, this causes that the file's …
> Diagnostic diff

- src/files/BrsFile.Class.spec.ts
- src/parser/Expression.ts
- src/util.ts
- src/validators/ClassValidator.ts
Fixes some bugs related to constructing new BrighterScript classes.
- fixed bug that wouldn't find the correct root-level class when calling `new` from within a namespace (fixes #203)
- fixed bug that was not adding an omitted namespace to a class whenever that class resides in the same namespace as the `new` statement.
> New statement namespace bugfix

- src/DiagnosticMessages.ts
- src/Scope.ts
- src/files/BrsFile.Class.spec.ts
- src/parser/Statement.ts
- src/validators/ClassValidator.ts
Calling `super()` in class constructor methods are current emitting bs1001 ("Cannot find function with name..."). This PR adds temporary relief for that issue by skipping bs1001 checks for any function call with the exact text "super" that is found in `.bs` files. This is slightly heavy-handed, but the current validation logic does not provide enough information to know if the parent function is a class method or not. 
In future validation enhancements we will tighten up this logic.
Also, this PR adds the ability for class constructors to have non-`m.` based statements before a `super()`  call. 
Fixes #202
> Skip validation for "super" function calls.

- src/files/BrsFile.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/statement/Misc.spec.ts
- src/util.spec.ts
- src/util.ts
- Drop expensive AST walking for collecting property names and instead collect them as part of parsing.
- Use visitor for `super` AST mod.
- Removed `util.findAllDeep`
> Performance refactoring: property names completion, classes transpilation

- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
improves diagnostic printing, by going to program to retrieve file contents, and allowing in-memory files to be used, not failing when there is no content, and improving efficiency
> Use in-memory source code for diagnostic printing

- src/Program.spec.ts
- src/Program.ts
- src/files/tests/imports.spec.ts
Massively improve validation performance by refactoring `getFileByPkgPath`.
Like 40% faster validation for me.
> Performance: refactored getFileByPkgPath

- src/Scope.spec.ts
- src/Scope.ts
- src/files/tests/imports.spec.ts
- src/globalCallables.ts
- src/interfaces.ts
- src/parser/tests/statement/Misc.spec.ts
- src/util.ts
Declaring a `sub constructor()` crashes the compiler.
Seems ok for properties, somehow, but I've added tests to control.
> Crash: reserved JS names

- docs/annotations.md
- docs/callfunc-operator.md
- docs/classes.md
- docs/imports.md
- docs/index.md
- docs/namespaces.md
- docs/plugins.md
- docs/source-literals.md
- docs/template-strings.md
- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Annotations are metadata expressions attached to AST statements.
- any statement can receive multiple annotations,
- annotations can be on the same line as the statement,
- annotations can have arguments; arguments can be any valid BrightScript expression,
- name of the annotation must be a valid identifier; it can't be a keyword (e.g. `sub`, `while`...),
- annotations have a method to obtain JS-friendly types (`annotation.getArguments()`); basic types, arrays and roAssocArrays are converted.
Limitation:
- annotations aren't validated if they are mis-named; could be declared by the plugins using them in the future,
- currently these expressions are not walked, for various reasons.
Example:
```brightscript
@someFlag
sub someFunction()
'...
end sub
@configuration("param", [1, 2, 3], { prop: …
```
> Feature: AST annotations

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/globalCallables.ts
Plugins and external consumers of `.brs`/`.bs` files should not need to know whether a file parsing has been skipped due to typedef loading. This PR addresses the issue by converting the `BrsFile.parser` into a getter, and parsing the file on-demand if the parsing was previously skipped.
> support on-demand parse for typedef-shadowed files

- CHANGELOG.md
- bsconfig.schema.json
- src/Program.spec.ts
- src/Program.ts
- src/util.spec.ts
- src/util.ts
- `emitDefinitions` now defaults to `false` (it previously defaulted to `true`)
- don't transpile `d.bs` files (which would produce `d.brs` files with duplicate information in them)
> emitDefinition fixes

- src/ProgramBuilder.ts
- src/files/BrsFile.spec.ts
- src/util.ts
When running through VS Code extension, plugins were loaded relatively to the extension, not the project.
> Load plugins relatively to the project

- src/lexer/TokenKind.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Parser.ts
Functions are not allowed to use certain keywords as names. BrighterScript didn't enforce this, but this PR fixes that issue.
Also added the try/catch token kinds which will be used in a future PR.
> flag functions with keyword names.

- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/Scope.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.ts
Catch when local variables and scope functions have the same name as a class.
Fixes #245
> Class name collision

- src/DiagnosticMessages.ts
- src/files/BrsFile.spec.ts
- src/interfaces.ts
- src/lexer/Lexer.spec.ts
- src/lexer/TokenKind.ts
- src/parser/Expression.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
- src/parser/tests/statement/Throw.spec.ts
- src/parser/tests/statement/TryCatch.spec.ts
Add support for try/catch statements and `throw` statements.
Resolves #218
> Try catch support

- package-lock.json
- src/astUtils/creators.ts
- src/diagnosticUtils.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
- src/parser/tests/Parser.spec.ts
The `vscode-languageserver-types` package introduced a breaking change between `3.15.1` and `3.16.0`, causing any new installs of `brighterscript` to immediately fail. This PR addresses those issues by avoiding calling `Range.create()` _anywhere_ in the regular code (unit tests were ignored for now since they're not failing).
> Fix Range.create rte due to bad vscode semver bump

- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
Fix syntax error for floats with more than 5 decimal places that also have an exponent component. 
Fixes #231
> Support long floats with exponents.

- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
According to the [BrightScript documentation](https://developer.roku.com/docs/references/brightscript/language/expressions-variables-types.md#type-declaration-characters), a `%` can be appended to an integer literal to enforce that it becomes an integer type. 
Currently bsc shows a syntax error on that trailing `%`, so this PR fixes that. 
Fixes #233
> Support integer type declaration char

- src/DiagnosticMessages.ts
- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/files/BrsFile.Class.spec.ts
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/TokenKind.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/controlFlow/For.spec.ts
- src/parser/tests/controlFlow/If.spec.ts
- src/parser/tests/controlFlow/While.spec.ts
- src/parser/tests/statement/Goto.spec.ts
- src/parser/tests/statement/Misc.spec.ts
- src/parser/tests/statement/Stop.spec.ts
- src/parser/tests/statement/TryCatch.spec.ts
- Make `ElseIf` into an `ElseIfStatement` so that `elseif`'s condition expression is in the context of an obvious statement,
- Refactored statement parsing wrt newline/colon,
- Improved error recovery with unclosed blocks when reaching `end sub/function`.
> AST parser refactoring

- src/globalCallables.ts
This is to support calls like this:
```
CreateObject("roScreen", true, 720, 480)
```
See https://developer.roku.com/docs/references/brightscript/components/roscreen.md
> CreateObject can take 4 parameters (roScreen)

- package.json
- src/astUtils/reflection.ts
Fix `isLiteralInvalid` function.
Also lock `vscode-languageserver-protocol` version to fix the broken transitive dependency resolution of `vscode-languageserver`.
> Fix "invalid" literal reflection

- .eslintrc.js
- package-lock.json
- package.json
- src/ProgramBuilder.ts
- src/examples/plugins/removePrint.ts
Disallow `Array.forEach` in this codebase because it serves no benefit, and can introduce performance problems. 
(You can still use it in `*.spec.ts` files if you wish)
> disable Array.forEach via eslint

- src/BsConfig.ts
- src/DiagnosticFilterer.spec.ts
- src/DiagnosticFilterer.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
E.g. accept `'bs:disable-next-line: CUSTOM123` and those in diagnostic filters.
- Support strings for diagnostic codes
- Don't validate strings for diagnostic codes
> Better support of plugins diagnostics

- docs/plugins.md
- src/ProgramBuilder.ts
- src/examples/plugins/removePrint.ts
- src/files/BrsFile.spec.ts
- src/interfaces.ts
- src/util.spec.ts
- src/util.ts
There is a flaw in the plugins system right now that always creates a singleton. which pushes the oweness of multi-projects on to each plugin. to combat this, the plugin system has been refactored to require plugins to register a singleton FACTORY, which returns a new plugin instance every time it's called.
> Plugins as factory

- src/parser/Parser.spec.ts
- src/parser/Parser.ts
Adds annotation support for classes, attaching any pending annotation…s that appear before a class keyword
@elsassph inspired (i.e goaded) me to add annotation support for maestro, perhaps knowing that this feature was missing and I would therefore have to write it :D Great delegation @elsassph 👏 
Hopefully this approach is okay - I'm sure we all concur that annotations are just as usefu on classes as other statements.
> Class annotation support

- benchmarks/targets/validate.js
- scripts/compile-doc-examples.ts
- src/FunctionScope.spec.ts
- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/Program.spec.ts
- src/Program.ts
- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/Scope.spec.ts
- src/XmlScope.spec.ts
- src/astUtils/visitors.spec.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- src/globalCallables.spec.ts
- src/interfaces.ts
- src/parser/Statement.spec.ts
- src/parser/tests/expression/SourceLiteralExpression.spec.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/preprocessor/Manifest.spec.ts
- src/util.spec.ts
- src/util.ts
Since the xml parser change removed the need for any async parsing, there's no benefit to having async file adding logic at all in the Program and downstream. Notable changes:
- remove all unnecessary async functionality from `Program`, `BrsFile`, `XmlFile`. 
- The `ProgramBuilder` still uses async logic when loading files because it yields a lot of performance benefits.
- Moved `fileResolver` logic out of `Program` and into `ProgramBuilder` so the language server can continue to use the in-memory `Document` stores
- Changed `fileResolver` into an object with `readFile` and `readFileSync` functions so we can use the proper function when needed.
- renamed `fileExists` to `pathExists` and `pathExistsSync` to line up with the ones from `fs-extra`
I broke the commits up so you can see just …
> Remove async file adding from program

- src/cli.ts
using `sourceMap` from bsconfig.json wasn't working when running from the cli. This was because the yargs `source-map` parameter had a default value, which was overriding the bsconfig value. Removing the default solved the problem.
> Fix sourceMap property in bsconfig

- src/Program.spec.ts
- src/Program.ts
- src/files/BrsFile.ts
The loop item in `for each` statements is not currently showing up in completions. [this pr](https://github.com/rokucommunity/brighterscript/pull/258) attempted to fix that, but it quickly morphed into an entirely different type of PR. 
This PR fixes the original issue. I did use the `walk` function, but only for `WalkMode.VisitStatements`. The local benchmarks show that the walk doesn't have any significant impact on performance (and remember these numbers are ops/sec for parsing the [Roku-GooglePhotos](https://github.com/chtaylo2/Roku-GooglePhotos) project) :
Once #258 lands, the code in this PR will be obsolete, but this helps bridge the gap in the short-term.
> ForEach item completions

- src/LanguageServer.ts
- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/util.spec.ts
- src/util.ts
Converts bsconfig file loading to use synchronous APIs. there's no tangible benefit to using async apis for loading the configs in sequential order.
> Load bsconfig.json synchronously

- src/parser/Parser.spec.ts
- src/parser/Parser.ts
Currently an empty annotation symbol `@` above class methods will cause an infinite loop in the parser. This fixes that issue.
> Annotation fixes

- src/astUtils/creators.spec.ts
- src/astUtils/creators.ts
- src/files/BrsFile.spec.ts
the `createStringLiteral` function was not wrapping the value in quotes, which was unintuitive since it's not obvious that TokenKind.StringLiteral's value should be wrapped in quotes. This PR wraps the value if the quotes are missing, or leaves the value alone if at least one quotemark is found.
> Better handling for `createStringLiteral`

- src/parser/SGParser.spec.ts
- src/parser/SGParser.ts
Fix issue where parser throws a nodejs runtime error anytime it encounters a standalone `<` token.
> Fix xml parse error

- src/Program.ts
While integrating the brighterscript compiler into a fairly-large project (1 `.bs` file, >900 `.brs` files, >150 `.xml` files), I noticed fairly high times while building, taking ~16s in the transpilation step alone.
Narrowed it down to a loop within `Program.transpile` which was iterating `fileEntries` (2113 items) trying to find a specific entry for every item in `Program.files` (1223 items), resulting in over a million iterations. The solution, while not very pleasant memory-wise, reduces the number of iterations to 3336, and transpilation of the same project now takes ~435ms.
> Improve transpilation performance by indexing fileEntries beforehand

- src/FunctionScope.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- shows labels in scope after `goto` keyword
- hovering a label name (after `goto` or at declaration location) says it's a label
- ctrl+click label (after `goto`) goes to the line of the label declaration
> Completion and code navigation for labels

- src/files/XmlFile.spec.ts
- src/files/XmlFile.ts
Fix bug with multiple-in-a-row transpiles for xml files that hadn't changed, would cause scripts to get mangled.
> Don't mangle xml scripts during transpile

- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
running the bsc cli in watch mode on a windows device is crashing on any file change. The issue was that certain terminals will force the drive letter to lower case. this fixes that.
> Fix watcher bug on windows devices.

- src/LanguageServer.ts
Ive seen a few times where I've had errors on getting signature completions. I dont' have time to work out what they are now (they're related to typing fast, with @. afaict); so this is a stop gap.
> catch errors when getting signatures

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
I spotted an issue where vscode would constantly update itself. There's some config file that get's updated whenever a user does pretty much anything, and sometimes in the background.
This meant that whole workspace revalidations would occur every time the user does anything in the ide, such as go to a symbol, show message tool tips, degbug, I suppost just about anything. In my case it was causing catastrophic performance issues culminating in whirring fans.
> do not revalidate on changes that are outside of any workspace

- src/globalCallables.spec.ts
- src/globalCallables.ts
- src/testHelpers.spec.ts
This is a temporary fix for the fact that `Roku_Ads` is _sometimes_ available globally (dependent on a `Library` import. 
Long-term we want to add formal `Library` handling. However, There's a lot of other more important things to work on right now, so this will hold us over until then.
Provides temporary relief for #179
> Intermediary fix for Roku_Ads error

- benchmarks/index.js
- benchmarks/target-runner.js
- benchmarks/targets/lex-parse-validate.js
- benchmarks/targets/lex.js
- benchmarks/targets/parse-brs.js
- benchmarks/targets/parse-xml.js
- benchmarks/targets/parse.js
- benchmarks/targets/transpile-brs.js
- benchmarks/targets/transpile-xml.js
- benchmarks/targets/transpile.js
Adds several improvements to the benchmark scripts:
- remove the `iterations` functionality (which ran multiple benchmarks and took the average) in favor of modifying the raw benchmark.js `minTime` parameter to run the tests longer, which achieves the same results with less complications
- rename several targets so their names sort better (i.e. `xml-parser` -> `parse-xml`, etc...)
- Show more frequent test status updates as the tests are running.
- Format the results better so the targets, versions, and ops/sec all line up properly
- add `--fast` flag to run a faster version of the benchmarks. our tests default to benchmark.js `minTime=2.5` (seconds), so `--fast` unsets that value so it defaults to benchmark.js's default `.05` seconds.
- add several new targets
- parse-brs
- transpile-brs …
> Benchmark improvements

- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
Centralizes all of the brs transpiling SourceNode line and column tracking into a single function.
- the previous `state.sourceNode` implementation did not convert 0-based Range line to 1-based SourceNode line. This fixes that problem and should improve debug precision
- remove use of `new SourceNode` from `Expressions.ts` and `Statements.ts`
- for token transpiling, use `state.tokenToSourceNode` which should have a slight performance bump since the token text is passed in by reference on the `token` reference rather than by value as the second parameter to `state.sourceNode`
- fixed a few small bugs in transpile
> Standardize sourcenode

- src/LanguageServer.ts
- src/Program.spec.ts
- src/Program.ts
Resolves an oversight in codeAction functionality where we weren't accounting for missing files or programs that didn't have the file.
Fixes #322
> codeaction don't fail on missing file

- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
When generating type definition files, include the namespace for every `extends` statement, just for clarity.
> include namespace for class extends in typedef

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Fixes null reference exception caused by activating completions on the first token in a file
> Prevent completion error for first token in file

- src/Program.ts
- src/files/BrsFile.ts
Compute `BrsFile.parseMode` during constructor rather than in a getter to reduce unnecessary processing.
> Set BrsFile.parseMode in constructor, remove getter

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
Fixes a critical bug in BrsFile that would crash entire file parsing if the file contained an immediately-invoked-function-expression. 
Also supports non-grouped IIFEs (gross, but technically valid syntax...so we should support it).
> Iife parse

- src/parser/Parser.ts
- src/parser/tests/controlFlow/If.spec.ts
Print statement parsing needs to stop when it reaches an `else`
Fixes #344
> Fix - print statement parsing

- README.md
- package-lock.json
- package.json
- src/Program.ts
- src/parser/Expression.ts
- src/parser/TranspileState.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/util.spec.ts
- src/util.ts
Adds:
- support for both npm aliased bslib AND non-aliased:
- `ropm install bslib@npm:@rokucommunity/bslib`
- `ropm install @rokucommunity/bslib`
Fixes:
- bug with npm alias of bslib for node version 10
- infinite loop when rewriting the bslib file during transpile.
> Bslib fixes

- src/Program.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
Also added a test with transpiling with custom types.
> Fixes #348 - Use 'toTypeString' method on transpilation of function return types

- src/parser/Expression.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
Fixes a bug where transpiling a template string with two side-by-side inline expressions were missing a plus to separate them.
Fixes #355
> Fix template string transpile bug.

- src/Program.spec.ts
- src/files/BrsFile.ts
Fixes a crash when `getClassFromMReference` would throw an exception when previousToken was null. 
#357 shows a stack trace where the code is crashing. I couldn't figure out the brightscript code to reproduce it, but I was able to write a unit test that causes the crash to occur, so I fixed it that way. 
Fixes #357
> onSignatureHelp stability fix

- src/DiagnosticMessages.ts
- src/Program.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.ts
- src/parser/Parser.ts
Add class import codeAction suggestions
Resolves #364 
- add code action to suggest file imports for unknown classes
- restrict function and class import code actions to .bs files only.
> Add class import code actions.

- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/SourceLiteralExpression.spec.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/testHelpers.spec.ts
Just some housecleaning. Moved the `getTestTranspile()` function into `testHelpers.spec.ts` so it's more easily discoverable.
> Move `getTestTranspile` into test helpers

- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
- src/parser/tests/statement/PrintStatement.spec.ts
> Retain print separators during transpile

- src/DependencyGraph.spec.ts
- src/DependencyGraph.ts
- src/Scope.ts
- src/files/XmlFile.ts
Resolves an issue where circular imports will cause an infinite notification loop in `DependencyGraph`. 
Fixes #377
> Prevent circular import crash

- src/parser/Parser.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
support concat string and template string, 
fixes #382
> Concat template string and string

- src/files/XmlFile.spec.ts
- src/files/XmlFile.ts
Fixes issue where `file.needsTranspiled = true` would be reset during certain stages of the plugin lifecycle.
> Fix needsTranspiled xml issue.

- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/parser/tests/expression/SourceLiteralExpression.spec.ts
- src/testHelpers.spec.ts
Updates `testTranspile` to check the program for diagnostics instead of just the file, and to use `expectZeroDiagnostics` for better diagnostic printing.
> validate transpile code

- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/files/BrsFile.Class.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/types/CustomType.ts
- src/validators/ClassValidator.ts
Fixes #391.
- allow class fields to be redeclared in child classes as long as the types are the same
- flag type differences between parent and child class fields with same name
- allow custom types for class field types
> Allow class field overrides, disallow type changes

- package-lock.json
- package.json
I heard that the bsc watch mode doesn't work with M1 macs. I don't have a mac, but I did find [this GitHub issue](https://github.com/paulmillr/chokidar/issues/1048) stating that a recent chokidar release supports mac M1, so i'm upgrading BSc to use that version. It shouldn't cause any issues? I'll need someone with an M1 mac to test this build out.
> Upgrade chokidar to support M1 macs

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/Program.spec.ts
- src/Program.ts
- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/Scope.spec.ts
- src/XmlScope.spec.ts
- src/astUtils/visitors.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- src/globalCallables.spec.ts
- src/parser/SGParser.spec.ts
- src/parser/Statement.spec.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/testHelpers.spec.ts
`addOrReplaceFile` is needlessly verbose. Similar to the javascript `Set` object, calling `setFile` is much more concise and accurately describes the operation.
> Rename `Program` `addOrReplaceFile` to `setFile`

- src/Scope.ts
Inside a namespace, incomplete classe or function statements can cause an exception.
> Incomplete statement in namespace can crash the server

- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/tests/expression/AssociativeArrayLiterals.spec.ts
For code-style validation we need to know whether a comma is present at the end of an AA member
> Extract AA comma when parsing

- src/files/BrsFile.spec.ts
- src/globalCallables.ts
> Allow up to 6 arguments to CreateObject to support roRegion

- src/DiagnosticMessages.ts
- src/astUtils/reflection.ts
- src/lexer/TokenKind.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
- src/parser/tests/statement/Misc.spec.ts
- src/testHelpers.spec.ts
- src/types/InterfaceType.spec.ts
- src/types/InterfaceType.ts
Adds `interface` statements to the language. This PR doesn't do much with them other than allow them to be parsed and included in the AST. Future PRs will probably do more with then.
Is there anything else we need to address in this initial PR?
> Adds language support for Interface statements

- benchmarks/index.js
- benchmarks/targets/hover-brs.js
- benchmarks/targets/parse-brs.js
- src/Scope.ts
- src/files/BrsFile.ts
Benchmark results:
```
% npm run benchmark -- --versions=local 1.0.0-alpha.9
> brighterscript@1.0.0-alpha.9 benchmark /Users/mpearce/redspace/roku/brighterscript
> node ./benchmarks/index.js "--versions=local" "1.0.0-alpha.9"
benchmark: Clearing any existing node_modules folder
benchmark: using versions: local,1.0.0-alpha.9
benchmark: build current brighterscript
> brighterscript@1.0.0-alpha.9 build /Users/mpearce/redspace/roku/brighterscript
> rimraf out && tsc
benchmark: pack current brighterscript
benchmark: Writing package.json
benchmark: npm install
npm WARN benchmarks No description
npm WARN benchmarks No repository field.
npm WARN benchmarks No license field.
added 151 packages from 207 contributors in 2.322s
7 packages are looking for funding
run `npm fund` for details
benchmark: …
```
> Caches lookups when checking for symbols on a token

- docs/readme.md
- docs/regex-literals.md
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/TokenKind.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/tests/expression/RegexLiteralExpression.spec.ts
Adds the ability to declare regular expression literals rather than dealing with strings. Example:
```brightscript
regexp = /[a-z]+/i
```
transpiles to
```
regexp = CreateObject("roRegex", "[a-z]+", "i")
```
Tasks:
> Add regex literal support

- src/Scope.spec.ts
- src/Scope.ts
- src/files/BrsFile.ts
- src/files/XmlFile.spec.ts
Fixes critical language server issue. 
```
Cannot read properties of undefined (reading 'pathAbsolute')
at Scope.detectVariableNamespaceCollisions (/Users/x/.nvm/versions/node/v14.16.0/lib/node_modules/brighterscript/dist/Scope.js:433:116)
at /Users/x/.nvm/versions/node/v14.16.0/lib/node_modules/brighterscript/dist/Scope.js:399:18
at Scope.enumerateBrsFiles (/Users/x/.nvm/versions/node/v14.16.0/lib/node_modules/brighterscript/dist/Scope.js:256:17)
at Scope._validate (/Users/x/.nvm/versions/node/v14.16.0/lib/node_modules/brighterscript/dist/Scope.js:394:14)
at /Users/x/.nvm/versions/node/v14.16.0/lib/node_modules/brighterscript/dist/Scope.js:381:18
at Logger.time (/Users/x/.nvm/versions/node/v14.16.0/lib/node_modules/brighterscript/dist/Logger.js:139:20)
at Scope.validate …
```
> Namespace fix

- docs/null-coalescing-operator.md
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/util.ts
Fixes an issue in the transpiled output of the null coalescing operator where plain variable references are not properly passed into the function.
> Null coalescing <uninitialized> fix

- docs/plugins.md
- src/Program.spec.ts
- src/Program.ts
- src/astUtils/AstEditor.spec.ts
- src/astUtils/AstEditor.ts
- src/interfaces.ts
Adds ability to edit AST during `beforeFileTranspile`, and then the changes are reverted after the `afterFileTranspile` event.
- Adds new `AstEditor` class that applies edits and tracks how to undo them.
- Adds `editor` property to the `beforeFileTranspile` and `afterFileTranspile` lifecycle events.
- Once the `afterFileTranspile` event has fired for all plugins, the `editor.undoAll()` method is called which will revert all of the AST changes made during the transpile flow.
- Update docs with example
- any files that were edited using `editor` will have the `needsTranspiled` property set to `true` automatically.
> AST editing

- package-lock.json
- package.json
- src/LanguageServer.spec.ts
- src/Program.spec.ts
- src/ProgramBuilder.spec.ts
- src/Scope.spec.ts
- src/XmlScope.spec.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- src/globalCallables.spec.ts
- src/parser/tests/expression/RegexLiteralExpression.spec.ts
- src/testHelpers.spec.ts
- adds new `expectDiagostics` and `expectHasDiagnostics` functions to streamline diagnostic checks in unit tests. (0e0927888fc608e19b2cdda94188fb7fed21a5f2)
- updates many unit tests to use these simplified test helpers. (e6d2978744d87c6a545bfc61bc51e8aa2912b93a)
> Add diagnostic test helpers

- src/Program.spec.ts
- src/files/BrsFile.ts
- src/files/XmlFile.ts
- src/interfaces.ts
- Adds `beforeFileValidate` plugin hook. While currently the `afterFileParse` event happens at roughly the same time, adding this new hook makes it more approachable to extension authors (i.e. they don't have to read the docs), and also guards against issues that may occur if we add events between `afterFileParse` and `beforeFileValidate` in the future. It also makes things more clear when doing pre-validate work, then doing post-validate cleanup.
- Adds `onFileValidate` plugin hook which is how where plugins should hook in when contributing their own file validations.
Since the v1 plugin system event parameters use a single event object (instead of 1...n parameters), all newly added plugin events in master will also follow that style to minimize impacts of plugins migrating to v1.
> Adds plugin hooks for file validation

- src/parser/Parser.spec.ts
- src/parser/tests/controlFlow/For.spec.ts
- src/parser/tests/controlFlow/ForEach.spec.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/statement/Dim.spec.ts
- src/parser/tests/statement/Throw.spec.ts
Importing from "barrel" files (like index.ts where all it does is import/export other files) can cause circular references. All of our internal code should be importing directly from files that contain the code they want to use.
> Don't import from `..` folders

- src/Program.ts
- src/astUtils/visitors.spec.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/files/XmlFile.spec.ts
- src/files/XmlFile.ts
Moves the `afterFileParse`, `onValidateFile`, and `afterFileValidate` events into the `Program` class and out of `BrsFile.ts` and `XmlFile.ts` to make things more consistent. 
The changes were mostly done to `BrsFile.ts`, `XmlFile.ts`, and `Program.ts`. The other changes are just unit test tweaks to make them work with the changes (i.e. we need to call `program.addOrReplaceFile` now instead of using the `file.parse()` function directly to trigger the plugin event.)
> Move parse and validate events out to program level

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/globalCallables.spec.ts
- src/types/FunctionType.spec.ts
- src/types/FunctionType.ts
Fixes a bug introduced in #479 that switched optional and required within the hover logic, when hovering over functions.
One small technically breaking change is renaming the `FunctionType` parameters from `isRequired` to `isOptional`. This aligns with the `isOptional` property change introduced in #479. I'm not sure if plugins utilize this feature or not, so they may need to be updated (we're still in v0 which is unstable, after all :D) 
Bad:
Fixed:
> Fix bug with optional parameters

- src/PluginInterface.ts
- src/Program.spec.ts
- src/Program.ts
- src/interfaces.ts
- The "preview transpiled code" feature in vscode utilizes the `getTranspiledFileContents` function. However, plugin-related changes were not showing. This resolves that issue.
- adds `code`, `map`, `typedef` properties to the `afterFileTranspile` event to allow plugins to manually tweak the output code (at their own risk). 
- mostly unrelated: return a reference to the plugin in the `add`, `addFirst`, and `remove` methods of the `PluginInterface` class.
> Fire plugin events for getTranspiledFile. Add new event properties

- src/Cache.ts
Adds generics support to the cache class to help typescript types flow better in our code.
Changes internal storage mechanism to a `Map` which is safer than an object because it prevents key collision with prototypes.
> Support generics for Cache class

- src/Program.spec.ts
- src/Program.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/files/XmlFile.spec.ts
- src/files/XmlFile.ts
moves the file validation logic out of `addReplaceFile` and into `program.validate()`. This accomplishes several things:
- aligns with the flow in v1 which makes more logical sense
- improve performance slightly when typing in an editor because file validations get deferred until the validate phase
- prevent file validation events on files shadowed by typedef files, which was a bug introduced in #494
This is technically a breaking change to the event flow. 
Event flow prior to this change:
- `afterFileParse`
- `beforeFileValidate`
- `onFileValidate`
- `afterFileValidate`
- `beforeProgramValidate`
Event flow after this change:
- `afterFileParse`
- `beforeProgramValidate`
- `beforeFileValidate`
- `onFileValidate`
- `afterFileValidate`
> Move file validation into  program.validate()

- src/Scope.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/types/ArrayType.spec.ts
- src/types/ArrayType.ts
- src/types/CustomType.ts
- src/types/FunctionType.ts
- src/types/LazyType.ts
- src/types/helpers.ts
- src/util.spec.ts
- src/util.ts
Adds fully parsed array type syntax
Allows for valid Brighterscript like:
```
function getSum(numbers as float[])
sum = 0.0
for each num in numbers
sum += num
end for
return sum
end function
function getTwoPis() as float[]
return [3.14, 3.14]
end function
sub main()
twoPi = getTwoPis()
myNumbers = [1.2, 4.5, twoPi[0] ]
print getSum(myNumbers)
end sub
```
> Array types

- src/astUtils/AstEditor.spec.ts
- src/astUtils/AstEditor.ts
In some situations, a plugin is unable to replace/remove an element from the AST (perhaps due to using an array from `Parser.references`). Without being able to replace/remove the elements themselves, overriding the transpile is a nice alternative. 
- adds a `overrideTranspileResult` method to the `AstEditor` which will return a sourcemap-enabled block of text to replace what would have been transpiled originally.
> Add transpile override to AstEditor

- src/diagnosticUtils.spec.ts
- src/diagnosticUtils.ts
Before the fix, line numbers larger than 9 would cause offset issues. This PR fixes the issue
> fix offset issue with diagnostic printing in cli

- src/parser/Statement.ts
- src/parser/tests/statement/For.spec.ts
- src/parser/tests/statement/ForEach.spec.ts
> Fixes bug with transpiling empty for loop #459

- src/astUtils/creators.ts
- src/astUtils/reflection.spec.ts
- src/parser/Statement.ts
Many of the creator functions need to call `createToken`, and then have to specify the token value. We know with certainty what some of those values are, so this PR auto-picks those default values when not explicitly specified.
Also adds `createClassMethod` creator for basic empty method creation.
> Adds default token values in creators. Simplifies class 'new' default builder

- src/parser/Expression.ts
- src/parser/Parser.ts
Removing the `isCalled` property on `VariableExpression` because it isn't used anywhere. It's probably left over from the `brs` runtime logic.
> remove VariableExpression.isCalled

- benchmarks/index.js
- src/DependencyGraph.spec.ts
- src/DependencyGraph.ts
- src/Program.ts
- src/files/BrsFile.ts
- src/files/XmlFile.ts
Fixes a memory leak when replacing files. 
**Before**
**After**
> Fix memory leak

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Fixes issue with outdated imports array when plugins change the import statement AST in BrsFile.
> Compute ownScriptImports after invalidateReferences()

- src/Logger.ts
- src/ProgramBuilder.ts
While diagnosing why the compiler is taking so long in our project, we noticed that the reported time is not correct.
After debugging a bit, I found that `stopwatch.stop()` was called right after `action(...)`, which doesn't work for async methods (which "Parsing files"/`loadAllFilesAST` is).
Moving the stop inside the `done` callback seems to do the trick.
> Fix logger.time() not returning accurate timings

- src/astUtils/creators.ts
- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
Fixes #534. 
The issue was that the `createClassMethodStatement` in `creators.ts` was incorrectly hardcoding the access type, when it should have been receiving that from the parameters. 
This type of bug is another reason why we should be using an options object instead of positional parameters for these...but that's a problem to solve some other time.
> Fix typedef auto-generated class constructor funcs

- src/Scope.spec.ts
- src/Scope.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/parser/Expression.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/util.spec.ts
- src/util.ts
- src/validators/ClassValidator.ts
Since Types are getting more complicated now, `TypeToken`s in `Expressions` and `Statements` have been refactored to being `TypeExpressions`
Also adds support for multidimensional arrays:
```
sub doLoop(data as float[][])
for each row in data
for each item in row
print item ' Brighterscript knows item is a float
end for
end for
end sub
```
> Adds TypeExpressions

- src/files/BrsFile.spec.ts
- src/types/BooleanType.ts
- src/types/DoubleType.ts
- src/types/DynamicType.ts
- src/types/FloatType.ts
- src/types/IntegerType.ts
- src/types/InvalidType.ts
- src/types/LongIntegerType.ts
- src/types/ObjectType.ts
- src/types/StringType.ts
- src/types/UninitializedType.ts
- src/types/VoidType.ts
- src/util.ts
When we transpile the code, we should retain the type tokens the exact way they were written. Previously, we were always transpiling them as all lower case.
> Keep the original type case when transpiling.

- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.spec.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
Fixes a bug in the BscPlugin that would crash whenever trying to transpile enums in a file not included in any scopes. Now the plugin will skip enum scanning entirely if the file isn't included in any scopes, or if the scope doesn't have any enums.
> fix crash when checking for enums to transpile

- src/files/BrsFile.spec.ts
Some of the plugin system tests depend on the code being transpiled (because they load `dist/examples/removePrint.js`). Since our unit tests run using ts-node, there are times when those files are not actually transpiled. The point of these tests is to make sure a plugin can be loaded, so this PR simply writes a new plugin to disk, removing the need to transpile before running the tests now.
> Don't depend on transpile to test plugins

- docs/interfaces.md
- docs/readme.md
- src/DiagnosticMessages.ts
- src/Program.spec.ts
- src/Scope.spec.ts
- src/Scope.ts
- src/astUtils/visitors.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
- src/types/BscType.ts
- src/types/CustomType.ts
- src/types/InterfaceType.spec.ts
- src/types/InterfaceType.ts
- src/util.ts
- src/validators/ClassValidator.ts
- Added Symbol tables to `InterfaceType`
- Refactored assignability to use symbol tables
- Refactored `InterfaceStatment` members - particularly `InterfaceMethodStatement` to more closely align with `ClassMethodStatement`
- Refactored InterfaceStatement parsing to use existing `functionDeclaration()` method
- `functionDeclaration()` changed to have an `options` parameter instead of flags, to make it more generic
- Added validation on Interfaces and interface members.
- Refactored `ClassValidator` to work with both interfaces and classes
- Token symbol lookup is compatible with Interfaces
Still TODO for interfaces:
- Hover support
- `implements` keyword
- Validation on `implements` keyword (e.g. if you're a class and you say you implement an Interface, make sure you do)
Lots of changes. …
> Adds Symbol Tables to InterfaceTypes - general refactor of Interfaces

- src/files/BrsFile.spec.ts
- src/types/helpers.ts
We should never have `undefined` for any object type in our type tracking system. This fixes one of those issues.
> Prevent `undefined` showing up in type tracking

- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/statement/TryCatch.spec.ts
Split the catch part into its a child statement of the try statement in order to facilitate source walking (for linting).
Add missing reflection methods.
> Refactor try-catch statement

- src/Scope.spec.ts
- src/files/BrsFile.spec.ts
- src/types/ArrayType.spec.ts
- src/types/ArrayType.ts
- src/types/BooleanType.spec.ts
- src/types/BooleanType.ts
- src/types/CustomType.ts
- src/types/DoubleType.spec.ts
- src/types/DoubleType.ts
- src/types/FloatType.spec.ts
- src/types/FloatType.ts
- src/types/IntegerType.spec.ts
- src/types/IntegerType.ts
- src/types/InterfaceType.spec.ts
- src/types/InterfaceType.ts
- src/types/InvalidType.spec.ts
- src/types/InvalidType.ts
- src/types/LazyType.ts
- src/types/LongIntegerType.spec.ts
- src/types/LongIntegerType.ts
- src/types/StringType.spec.ts
- src/types/StringType.ts
- src/types/TypedFunctionType.spec.ts
- src/types/TypedFunctionType.ts
- src/types/helpers.ts
In BrightScript, the `object` type can represent every type except `uninitialized`. This PR aligns the type system with that assumption.
> Better handling of `object` types

- package.json
- src/cli.spec.ts
- src/cli.ts
Adds the ability to `require` external modules as part of the CLI startup process. This allows bsc users to hook up things like ts-node/loader to run their plugins as pure typescript instead of needing a transpile step. 
Usage example:
```bash
npx bsc --require ts-node/register --plugins ./plugin.ts
```
> Adds support for requiring external modules on startup

- src/files/XmlFile.spec.ts
- src/parser/SGParser.ts
- src/parser/SGTypes.ts
When transpiling xml attributes, make sure to use the original quote character instead of always using `"`. This was fixed in the v1 branch, but is a big enough issue that it needed to be fixed in v0 as well. 
Fixes #549
> Retain quote char when transpiling xml attributes

- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/statement/PrintStatement.spec.ts
The comma is optional for mutli-line arrays associative arrays. The transpiler does not need to include them, excluding them would result in a very small size decrease for generated code.
> Don't add trailing commas for array and aa literals

- src/cli.ts
Right now, plugins have no way to be configured from the CLI. Plugins could try to load .env or environment variables, or they could look for custom options in the bsconfig. However, there is a valid use case for supporting custom cli arguments. 
I considered allowing plugins to contribute cli argument specifications, but that can happen in a future update.
The current solution is: don't fail on unknown cli arguments. it's a one-liner, and solves the problem.
> Disable strict cli args to empower plugins

- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/parser/tests/statement/Enum.spec.ts
Fixes a bug when transpiling enums used within binary expressions that wouldn't actually move the values inline.
> Fix enum transpile bug for binary expressions

- src/astUtils/visitors.ts
Statements added:
- `DimStatement`
- `InterfaceStatement`
- `InterfaceFieldStatement`
- `InterfaceMethodStatement`
- `TryCatchStatement`
- `CatchStatement`
- `ThrowStatement`
Expressions added:
- `FunctionParameterExpression`
- `AAMemberExpression`
- `AnnotationExpression`
- `TernaryExpression`
- `NullCoalescingExpression`
- `RegexLiteralExpression`
> Added missing statements and expressions to `createVisitor`

- docs/ternary-operator.md
- src/files/tests/optionalChaning.spec.ts
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/TokenKind.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/util.ts
Adds syntax support for optional chaining. Since the brightscript runtime supports this natively in Roku OS 11, there's no need for any special transpile logic at this time. However, there are significant dangers of crashing in the native implementation, so I think we will still add a transpile step in the future to make this feature more useful.
This PR is just to support the syntax from a parser level.
> Optional chaining

- src/Scope.spec.ts
- src/Scope.ts
- src/bscPlugin/BscPlugin.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/util.ts
This PR broke the functionality into 3 parts. 
- move `CreateObject` validation into the BscPlugin file with no logical changes e733c2d552e49a5732b69137910685726ebe4ee0
- add dedupe logic for CreateObject validations across multiple scopes 6b9e89eb13008a42bad178c5e90431b045a78422
- prevent `CreateObject` diagnostics for component library components a09fe6de52c79e6b562e7226ed6e7471c10c145c
> Create object fixes

- src/PluginInterface.ts
- src/Program.spec.ts
- src/Program.ts
- src/index.ts
- src/interfaces.ts
Adds `AstEditor` to `beforeProgramTranspile` and `afterProgramTranspile` plugin events in case a plugin needs that level of granularity.
> Add AstEditor to before/after programTranspile events

- src/Program.spec.ts
- src/Program.ts
- src/interfaces.ts
Updates `Program.transpile()` to loop through any newly added files that weren't there at the the start of the transpile cycle. 
For example:
plugin wants to inject some code into the `init()` function of a component. However, certain components don't have an init function and don't even have any scripts. So, during the transpile cycle, the plugin will auto-create new files for each component that is missing the init function. Then, afterwords the plugin will delete that file again.
> Transpile files added after start of transpile cycle

- src/Scope.spec.ts
- src/Scope.ts
- src/SymbolTable.ts
- src/astUtils/reflection.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/types/EnumType.ts
Adds `EnumType`s, and allows enums to be used as parameter types and return values.
Due to the weirdness of enums, I elected to actually define members as a different type than the Enum itself, but we can assign a member to a value of the EnumType.
When enums are used as parameter types, arguments are correctly validated.
> Adds enum types

- src/Scope.ts
- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
Updates scope validation to allow enum and interface names as function parameter types.
> Allow interfaces and enums as function param types

- src/astUtils/creators.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/astUtils/visitors.ts
- src/files/BrsFile.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/validators/ClassValidator.ts
#575 will need to reuse the `ClassFieldStatement` and `ClassMethodStatement`. This PR renames those to `FieldStatement` and `MethodStatement` respectively so they apply more generically across the project.
Backwards compatibility is retained by some javascript trickery, but these items will be removed in v1.
> Rename `ClassFieldStatement` and `ClassMethodStatement`

- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
Fixes a bug where enums inside if statements weren't being colored properly by semantic tokens.
> Fix semantic tokens for enums in if statements

- src/parser/Statement.ts
All BrighterScript classes must have a `new` method at runtime. To prevent unnecessary code, brighterscript automatically emits an empty `new` method during transpile. However, it was doing this by actually injecting the method into the class's body AST. This can cause issues in plugins that depend on adding/removing methods as part of AstEditor operations. 
This PR resolve that issue by emitting the `new` method without adding it to the class body's AST.
> Don't push synthetic constructor into each class

- src/LanguageServer.ts
- src/util.ts
roku-deploy uses cwd when looking for `bsconfig.json` and `roku-deploy.json`. However, when running the language server in multi-workspace mode, `process.cwd()` is the _first_ workspace folder. This causes roku-deploy to use the wrong bsconfig.json for workspaces without a `files` array.
The issue has been fixed by using the `DefaultFiles` array from roku-deploy instead of calling `rokuDeploy.getOptions().files`.
> Fix cwd issue with multi-root workspaces

- src/DependencyGraph.spec.ts
- src/DependencyGraph.ts
Adds support for an array of keys in the `DependencyGraph.getAllDependencies()` method.
> Allow multiple keys for DependencyGraph.getAllDependencies

- src/astUtils/AstEditor.spec.ts
- src/astUtils/AstEditor.ts
- src/interfaces.ts
Adds an `AstEditor.edit` method that allows plugin authors to run a function to apply, and another function to undo. This allows for things like calling methods on objects rather than directly manipulating arrays or properties.
> Add function-based AstEditor.edit method

- src/astUtils/visitors.spec.ts
- src/astUtils/visitors.ts
Currently the AST walkers support transforming the AST by returning a new statement/expression. However, this does not work well in watch mode because those are permanent transformations. 
This PR adds an option to provide an `AstEditor` as part of the `WalkOptions`, so those edits will be done using the `AstEditor`, therefore enabling this pattern for watch mode plugins.
> Support AstEditor in visitor editing pattern

- src/Scope.spec.ts
- src/Scope.ts
Fixes bug preventing enums and interfaces from being used as function return types.
> Allow Enum and Interface return types

- src/astUtils/visitors.spec.ts
- src/astUtils/visitors.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- Provides the parent object and the key used to fetch the item from the parent object in AST walk visitor callbacks. This makes AST editing a little easier when it's desired to actually remove the element from the parent AST. 
- update all AST `walk` methods to support adding/removing items during the walk cycle without messing up the iteration.
Also 
Resolves #477
> Add object and key to visitor callbacks.

- src/LanguageServer.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/tests/statement/Enum.spec.ts
Certain enums weren't being transpiled property. This was because expressions inside of `BinaryExpressions` were totally missing from the `references.expressions` collection. This fixes that issue.
fixes #604 
Fixes some enum highlighting bugs
> Fix bug that wasn't transpiling enums in binary expressions

- src/parser/Statement.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
- src/testHelpers.spec.ts
Fixes a bug where the `range` for `InterfaceStatement` was always null. This also resulted in transpile failures in certain situations.
> Fix missing range on interface statement

- src/Program.ts
Fix crash during transpile that would crash if the file was replaced in the `beforeProgramTranspile` or `beforeFileTranspile` events, as the transpiler was using the old file reference instead of the new one.
> Fix transpile crash when file was changed in beforeTranspile events

- scripts/compile-doc-examples.ts
- src/LanguageServer.spec.ts
- src/Program.spec.ts
- src/Program.ts
Emit the `beforeProgramTranspile` and `afterProgramTranspile` events anytime the The `preview transpiled code` action in the language server is executed. Some plugins need to run code during that event before the `beforeFileTranspile` event is triggered. This enables a more accurate transpile preview.
This is _technically_ a breaking change for anyone calling the `Program.getTranspiledFileContents` function because it's now async. However, I don't think it's being used that often.
> Emit before/after programTranspile during file transpile preview

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
Improves nested project discovery in the language server. Now, if no bsconfig.json files are found, the language server scans all nested directories for `manifest` files. Of those manifest files, if we find a `./source` folder with at least one .bs or .brs file, we now consider that a Roku project.
> Better project detection by language server

- CHANGELOG.md
- package-lock.json
- package.json
- src/Cache.ts
- src/DiagnosticMessages.ts
- src/Program.spec.ts
- src/Program.ts
- src/Scope.spec.ts
- src/Scope.ts
- src/SymbolTable.spec.ts
- src/SymbolTable.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/files/tests/imports.spec.ts
- src/files/tests/optionalChaning.spec.ts
- src/globalCallables.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/testHelpers.spec.ts
- src/types/DynamicType.ts
- src/validators/ClassValidator.ts
This PR finds usage of all variables that have not been defined. 
This is overlapping functionality with bslint's `LINT1001` rule, but we need this to do additional logic, and it's something a compiler should do natively anyway. LINT1001 is slightly superior in that it also detects "used before defined" errors, but they are not flagged that way in bslint and are included in the same LINT1001 bucket.
This adds basic symbol table support as well, just for name tracking purposes.
> Flag usage of undefined variables

- src/DiagnosticMessages.ts
- src/Program.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/files/tests/optionalChaning.spec.ts
- src/parser/Parser.spec.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/parser/tests/statement/PrintStatement.spec.ts
Add diagnostics for unsupported statements that are declared at the root of the file or within a namespace body. Like this:
> No top level statements

- src/Program.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/util.spec.ts
- src/util.ts
There was a bug where codeactions wouldn't work on the leftmost or rightmost part of a token. This fixes that, so now they'll be present on the edges as well.
> Support codeactions at the edges of tokens.

- docs/plugins.md
- docs/source-literals.md
- scripts/compile-doc-examples.ts
- Sync the latest `CompilerPlugin` interface every time the `npm run docs` command is run
- Add missing plugin lifecycle event information
- Prevent `SOURCE_LOCATION` and `SOURCE_FILE_PATH` docs from transpiling those specific examples
> Better plugin docs

- src/index.ts
Re-export `SemanticTokenTypes` and `CodeAction` from `vscode-languageserver` to support plugins who register `onGetCodeActions` and `onGetSemanticTokens` handlers.
> Export some vscode interfaces

- package-lock.json
- src/LanguageServer.ts
- src/Program.ts
- src/bscPlugin/hover/HoverProcessor.ts
- src/interfaces.ts
- Force all plugin hover contributions to be a markdown string or array of markdown strings, and then return those to the vscode client in an array so they get displayed with proper separators. 
- Remove hardcoded test entries in language server
> Fix bug in languageserver hover provider

- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/util.ts
Adds semantic token support for coloring const references. Notice how the const declarations and usages are _slightly_ darker than the regular variables.
> Add semantic token color for consts

- src/SymbolTable.ts
Adds a `toJSON` function to SymbolTable to help when debugging them.
> Add a `toJSON` function to SymbolTable

- src/Program.ts
- src/SymbolTable.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Several fixes:
- link every child expression/statement to its parent at the beginning of the `onFileValidate` event. This highly simplifies language service based queries that need to walk up the expression chain to find parent expressions or statements
- use AST walk for BrsFile validation instead of `references`
- add `getSymbolTable()` to every AST node to simplify finding the correct symbols.
> Link children to their parents in AST

- src/Scope.spec.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/tests/statement/ConstStatement.spec.ts
- add assignment expression values that are not within BinaryExpression to the `references.expressions` list.
- For constants in assignment expressions, fixes in:
- transpile
- semantic tokens
- hover
- validation
> Fix missed const references during transpile, hover, and semantic tokens

- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/interfaces.ts
- src/parser/Expression.ts
Fixes ts error introduced in #650 introduced that only shows up in the typedef files. 
Seems to provide a _slight_ performance boost as well (probably due to the `if (childNode?.parent)` check which prevents duplicate reparenting.
> Fix typescript error for ast parent setting

- src/Scope.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/testHelpers.spec.ts
Fix issue when building multi-scope diagnostics where bsc wasn't taking the actual file path into consideration. So it was incorrectly grouping all diagnostics together by code+message+range without considering file path. 
Also makes the expectDiagnostics function more flexible so it can check for file paths and relatedInformation.
> Fix scope-specific diagnostic grouping issue

- src/Program.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
> Dedupe code completions in components

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
Prevent several crashes related to the language server incorrectly assuming that all clients support "workspace/configuration".
> Fix crashes for clients that don't support "workspace/configuration" requests

- src/parser/Parser.ts
- src/parser/tests/statement/ConstStatement.spec.ts
- Fixes a bug that was preventing the use of `const` as a variable name.
- warn about using `const` statements in non-brighterscript mode
> Allow const as variable name

- src/Program.spec.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
Fixes compile-time crash when trying to transpile a file that's not included in any scope.
Fixes #666
> Fix compile crash for scope-less files

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
Fixes bug in language server introduced in #667 that wasn't actually reading the configuration data from vscode.
> Fix brightscript.configFile workspace config bug

- src/bscPlugin/BscPlugin.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/XmlFileValidator.ts
- src/files/BrsFile.ts
- src/files/XmlFile.ts
Moves remaining `XmlFile` and `BrsFile` validation logic into the `BscPlugin.onFileValidate` event hook. There is now no extraneous validation happening within those file classes.
> Move file validation into BscPlugin

- src/Program.ts
> use outputPath to check if thi is a new file

- src/Program.spec.ts
- src/Program.ts
- src/util.ts
Moves the `src;dest;` sanitizing into a function for reusability and testability.
> Centralize file path normalization for Program

- package-lock.json
- src/Program.ts
- src/Scope.ts
- src/astUtils/AstEditor.ts
- src/astUtils/creators.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/astUtils/visitors.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/index.ts
- src/interfaces.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/util.ts
Creates a superclass `AstNode` that both `Expression` and `Statement` extend.
> Create common ancestor for Expression and Statement

- src/Scope.ts
- src/files/BrsFile.ts
- src/parser/Parser.ts
- src/validators/ClassValidator.ts
Renames references to `isClassFieldStatement` and `isClassMethodStatement` in favor of `isFieldStatement` and `isMethodStatement`
> Rename refs  to isClass(field|method)Statement

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/tests/expression/ArrayLiterals.spec.ts
- src/parser/tests/expression/AssociativeArrayLiterals.spec.ts
- src/parser/tests/expression/Call.spec.ts
- src/parser/tests/expression/Indexing.spec.ts
- src/testHelpers.spec.ts
Does not give up so easily when an expression can't be parsed - will continue looking at further expressions.
Examples:
- `DottedGetExpressions` ending in a `.` -> first part is parsed as an expression and added to the AST
- `CallExpressions` -> if there is no closing `)`, or if an argument is unable to be parsed, the call expression is still added to the AST
- `ArrayLiteralExpression`  if there is no closing `]`, or if an element is unable to be parsed, the ArrayLiteralExpression is still added to the AST
- etc. (see tests!)
This has the nice side effect of provide WAY more diagnostics - so diagnostics like "Unmatched Bracket" actually show up, instead of "Unexpected newline", as well as being able to provide diagnostics on multiple problem arguments in the same function call.
> Finds and includes more deeply embedded expressions

- src/parser/AstNode.spec.ts
- src/parser/AstNode.ts
Adds functions to `AstNode` to help find child nodes.
> Add AST child searching functionality.

- src/Program.spec.ts
- src/Program.ts
Adds support for `pkg:/` prefixed paths in `setFile`. This makes the entire process more flexible, and moves closer to the v1 approach. Also will be useful in #408 so that plugins always provide `pkg:/` paths.
> Support `pkg:/` paths for `setFile`

- src/FunctionScope.spec.ts
- src/Program.spec.ts
- src/Scope.spec.ts
- src/Scope.ts
- src/XmlScope.spec.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- Eliminate the `{src;dest}` object structure in most unit tests since the `src` and `dest` never change. Instead, favor passing in the relative-to-rootdir path (i.e. the `pkgPath`). 
- improve the performance and flexibility of `Scope.getFile()`. (All the benchmarks seem to show no improvement, but it was still a good refactor)
> Optimize Scope.getFile(). Simplify setFile in tests.

- src/LanguageServer.spec.ts
- src/Program.spec.ts
- src/ProgramBuilder.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.spec.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- src/files/tests/optionalChaning.spec.ts
- src/globalCallables.spec.ts
- src/parser/AstNode.spec.ts
- src/parser/SGParser.spec.ts
- src/parser/Statement.spec.ts
- src/parser/tests/statement/ConstStatement.spec.ts
- src/parser/tests/statement/Continue.spec.ts
- src/parser/tests/statement/Enum.spec.ts
- src/parser/tests/statement/For.spec.ts
- src/parser/tests/statement/ForEach.spec.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
- src/parser/tests/statement/PrintStatement.spec.ts
- src/testHelpers.spec.ts
- src/util.spec.ts
Centralize all unit test paths.
Rename tmpDir to tempDir in tests.
Rename stagingFolderPath to stagingDir in tests.
> Unit test cleanup

- README.md
- bsconfig.schema.json
- src/BsConfig.ts
- src/Program.spec.ts
- src/Program.ts
- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/files/BrsFile.Class.spec.ts
- src/files/XmlFile.spec.ts
- src/files/tests/imports.spec.ts
- src/files/tests/optionalChaning.spec.ts
- src/globalCallables.spec.ts
- src/parser/AstNode.spec.ts
- src/util.ts
roku-deploy added new `stagingDir` and `retainStagingDir` options that more closely align with the other property names. This PR aligns BrighterScript with those new names as well
> Migrate to `stagingDir` away from `stagingFolder`

- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
This PR adds a method `isThrowStatement`, similar to other methods in `reflection.ts` to let plugins easily know if a givent statement is a `throw`.
> Expose an 'isThrowStatement' utility function for plugins

- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
Fix transpilation output for an else block with leading comment. (Fixes #555)
The range of a `Block` always starts with the range of its first statement.
In the case of a simple `else`, the value of `elseBranch` is a Block, which means we can't use it as the lineage marker -- in this case we can pass the `else` token itself to distinguish between a same-line and next-line comment.
- All existing unit tests pass.
- New unit test passes.
> Fix: else block with leading comment

- src/DiagnosticMessages.ts
- src/files/BrsFile.spec.ts
- src/parser/Parser.ts
Improve the range highlighting for bs1042. Previously it would highlight the _next_ token. ![image](https://user-images.githubusercontent.com/2544493/196270530-7cb83a1d-888b-4bfb-90f7-f7aee2ec9e97.png)
Now it highlights the entire `end sub` or `end function` token.
> Better token underline range for bs1042

- package-lock.json
- package.json
- src/Program.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Prevent variable shadowing in blocks.
> Fix if statement block var bug

- src/bscPlugin/hover/HoverProcessor.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
The parser currently scraps an entire function when encountering a parameter having an unknown type. This is a bit too aggressive. 
This PR improves that flow by recovering more gracefully by adding a diagnostic but then just keeping the unknown token as-is. 
This PR also fixes a few small runtime exceptions when interacting with files that aren't a part of any scope.
> better parse recover for unknown func params

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
Fixes an issue where the "get semantic tokens" language server request would cause the scope to cache namespace information _before_ the scope was actually ready, causing strange errors in the editor.
> semanticToken request wait until validate finishes

- src/Scope.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.ts
- src/parser/Statement.ts
There were 2 semi-independent issues here:
- Class assignability was not properly checked, so that a class overriding fields of its superclass with subclasses was causing an error
- getting typedefs using Classes as field types defined in another file
> Fixes issues around using classes as field types

- src/Scope.ts
- src/SymbolTable.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Adds a `name` property to SymbolTable to assist with debugging them.
> Add name to symbol table

- src/parser/Parser.ts
- src/parser/tests/statement/Continue.spec.ts
Allow `continue` to be used as local variable.
> Allow `continue` as local var

- README.md
As mentioned in a conversation in the RokuCommunity slack, the authoritative documentation on the `files` field lives in the `roku-deploy` documentation. This PR copies this documentation into the README here.
The new documentation is much longer than would fit in a bulleted list, so I restructured the surrounding document to use a series of paragraphs rather than a list. As part of this restructuring I tweaked a bit of formatting and added clarification to points that confused me.
I considered leaving the bulleted list intact and pulling the `files` field's documentation into its own markdown file in the `docs` directory. Please let me know if you would prefer that I take that approach instead. Even if the reformatting I did is kept intact I think extracting an additional markdown file …
> Copy information on files field from roku-deploy and restructure bsconfig section of README

- src/SymbolTable.ts
Fixes a stackoverflow/circular reference issue in `SymbolTable.toJSON()` by eliminating the `parentStack` property.
> Remove parentStack to prevent circular references

- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.spec.ts
Fixes #699 by preventing namespaces from being used directly as variables, since they don't exist at runtime.
> Prevent namespaces being used as variables

- src/Scope.ts
- src/files/BrsFile.spec.ts
Significant performance boost by caching callables (i.e. functions/subs) in scopes the same way we cache namespaces, enums, etc.
For an internal large project:
**before:**
```
[03:43:49:7760 PM]  Validating project finished. (5s851.115ms)
[03:43:58:0450 PM]  Validating project finished. (5s741.213ms)
```
**after:**
```
[03:43:20:6070 PM]  Validating project finished. (1s60.487ms)
[03:43:22:6610 PM]  Validating project finished. (1s214.548ms)
```
> Cache `getCallableByName`

- src/files/BrsFile.Class.spec.ts
- src/parser/Statement.ts
Fixes a bug when transpiling classes that was causing a double `super()` call in the transpiled output. This was caused anytime there was a comment as the first statement in a class `new()` body. 
Now we look for the first _non_ comment in the `new()` body.
> Prevent a double `super` call in subclasses

- src/astUtils/visitors.ts
Adds the `owner` and `key` parameters for the `DottedSetStatement` visitor
> Add missing visitor params for DottedSetStatement

- README.md
- bsconfig.schema.json
- src/BsConfig.ts
- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/util.ts
Using the `as type` syntax for parameters and return type on function seems to have a performance impact on Roku channels. 
This PR adds a `useExplicitType` configuration option to let the Brighterscript transpiler omit those to generate code that will be more efficient.
> Let users use or discard explicit types

- src/ProgramBuilder.ts
Adds throttling to the `ProgramBuilder.transpile()` function to enforce a single running transpile at a time.
> Throttle transpiling to prevent crashes

- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
Typedefs should include enum and interface information in function parameter and function return types.
Fixes #756
> Ensure enums and interfaces persist in typedefs

- scripts/test-related-projects.ts
- src/PluginInterface.ts
- src/parser/Expression.ts
- Use the system tempdir instead of a local .tmp folder, this prevents node from finding ancestor `node_module` folders, which can cause issues when testing certain projects.
- Reenable rooibos tests now that they're working properly.
- add maestro-bsc-plugin
> Fix test-related-projects. Reenable rooibos

- package-lock.json
- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
Passing more than 5 arguments to a callFunc method will crash the app.
Adds a diagnostic message if more than 5 arguments are passed.
> Add diagnostic for passing more than 5 arguments to a callFunc

- src/Program.spec.ts
- src/Program.ts
- src/bscPlugin/BscPlugin.ts
- src/bscPlugin/validation/ProgramValidator.ts
Created a `ProgramValidator` class that handles before/after validation items at the program level. 
moved the `this file isn't referenced anywhere` logic into that validator.
> Move not-referenced check into ProgramValidator

- src/parser/Parser.ts
- src/parser/tests/statement/Function.spec.ts
Fixes a crash in the parser when a function body fails to parse. Allows the diagnostics to happen, but still adds an empty `Block` entry to `function.body` so ast walkers have a better time.
> Fix crash when func has no block

- src/DiagnosticMessages.ts
- src/files/tests/optionalChaning.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Fixes #770 by including the missing ? in dotted get assignments that use optional chaining. (this isn't valid syntax, but the transpiler should still generate the code).
> Fix transpile bug with optional chaning

- src/parser/Expression.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
Wraps transpiled template strings in parentheses so they can be interacted with as a single expression. 
Fixes #787
> Wrap transpiled template strings in parens

- src/FunctionScope.ts
- src/Scope.ts
- src/bscPlugin/hover/HoverProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- Changes `FunctionScope.variableDeclarations` to use the `getType()` function instead of a statically-set `type`.
- `VariableDeclaration.getType()` reaches into the underlying expression/statement to derive the type 
Note:
We can probably refactor to remove `VariableDeclarations` AND `FunctionScopes` altogether, but I'm going for SMALL PRs. haha
> Removes Parsetime Static Type Setting

- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/hover/HoverProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.spec.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/testHelpers.spec.ts
- src/types/ReferenceType.spec.ts
- src/types/ReferenceType.ts
Adds `ReferenceType`
A `ReferenceType` is a `BscType` that is given a `SymbolTableProvider`, so that it can do lookups in a symbol table.
This is useful for when a type is unknown at parse time - eg. when a function is defined in a different file (or even just further down a file)
An additional change here is to make sure SymbolTables are linked for the appropriate scope when doing a hover.
> Adds ReferenceType

- src/Scope.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/parser/tests/statement/Enum.spec.ts
Fixes a bug that was incorrectly flagging namespace-relative enum values.
> Fix namespace-relative enum value

- src/parser/AstNode.ts
Small performance boost by optimizing the `AstNode.getSymbolTable()` method. 
Before: 
After (i.e. this change)
> Improves performance in symbol table fetching

- benchmarks/package-lock.json
- benchmarks/package.json
- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/types/BscType.ts
- src/types/CustomType.ts
- src/types/EnumType.ts
- src/types/NameSpaceType.ts
- src/types/ObjectType.ts
- src/types/ReferenceType.spec.ts
- src/types/ReferenceType.ts
- src/validators/ClassValidator.ts
- Fixed issues with Namespaces and invalid things being used as types
- Adds new error `itemCannotBeUsedAsType`
-  Properly finds the first expression in a chain that can not be resolved.
-
> Refactored `getType` to correctly use `SymbolTypeFlags`

- benchmarks/package-lock.json
- src/Scope.spec.ts
- src/Scope.ts
- src/SymbolTable.ts
- src/astUtils/reflection.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.Class.spec.ts
- src/parser/Expression.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/types/BscType.ts
- src/types/ClassType.spec.ts
- src/types/ClassType.ts
- src/types/EnumType.ts
- src/types/InheritableType.ts
- src/types/InterfaceType.spec.ts
- src/types/InterfaceType.ts
- src/types/NameSpaceType.ts
- src/types/ObjectType.ts
- src/types/ReferenceType.spec.ts
- src/types/ReferenceType.ts
- src/validators/ClassValidator.ts
- Changes `CustomType` to `ClassType`
- Refactors `InterfaceType` to behave more like other types
- Introduces abstract `InheritableType` that wraps code common to InterfaceType and ClassType
- Allows inheritable properties to be accessed from an interface or class instance
- Modifies InterfaceStatement & ClassStatement so that parents are TypeExpressions
- Changes diagnostic when no identifier is after `as` to be 'Identifier Expected after "as"...' instead of "unexpected token 'as' "
> ClassType and InterfaceType refactor and Inheritance

- src/Scope.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.Class.spec.ts
- src/parser/Statement.ts
- src/types/BscType.ts
- src/util.spec.ts
- src/util.ts
- src/validators/ClassValidator.ts
- Adds options to all `AstNode.getType()` calls
- Each AstNode is Responsible for adding to the the passed-in type chain
- Added Utility function to process a type chain
> Type chain refactor

- docs/namespaces.md
Fix syntax formatting on the [docs/namespaces.md](https://github.com/rokucommunity/brighterscript/blob/master/docs/namespaces.md) page
> Fix docs/namespace.md syntax formatting

- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/astUtils/visitors.ts
- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/util.ts
`NamespacedVariableNamedExpressions` are now either `VariableExpressions` or `DottedGetExpressions`
*this PR is ready for reveiw*
> Removes `NamespacedVariableNamedExpressions`

- README.md
- benchmarks/package-lock.json
- benchmarks/package.json
- docs/readme.md
- docs/union-types.md
- package-lock.json
- package.json
- src/BsConfig.ts
- src/CacheVerifier.ts
- src/Scope.spec.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/types/helpers.ts
- src/util.ts
I believe this is the last PR needed for Phase 1 of typing improvements.
- Adds `enableTypeValidation` bsOption flag. When this is false (which it is by default), then the validation is the same as before this change.
- Adds documentation about `union types` and `enableTypeValidation` flag
`enhancedTypeValidation = false`
```
npm run benchmark
> brighterscript@0.65.0 benchmark
...
benchmark: Running benchmarks:
lex-parse-validate@local  ---------- 11.777 ops/sec
lex-parse-validate@0.65.0 ---------- 13.699 ops/sec
lex@local  ---------- 85.062 ops/sec
lex@0.65.0 ---------- 83.016 ops/sec
parse-brs@local  ---------- 24.819 ops/sec
parse-brs@0.65.0 ---------- 25.128 ops/sec
parse-xml@local  --------- 294.343 ops/sec
parse-xml@0.65.0 --------- 300.521 ops/sec
parse@local  ---------- 73.236 …
```
> Adds `enableTypeValidation` flag and documentation

- src/files/BrsFile.Class.spec.ts
- src/parser/Statement.ts
Hi, I've encountered the same issue described [in this slack thread](https://rokudevelopers.slack.com/archives/CKF1QQGTY/p1685740439381379), which is preventing my team from adopting Rooibos's code coverage feature. It was mentioned in the thread that the current behavior of only looking at the first statement of a constructor in order to find a `super` call may be a bug. Here is my attempt at a fix. I hope it's helpful, please let me know if there are any changes needed to it.
> Fix injection of duplicate super calls into classes

- src/Scope.spec.ts
- src/Scope.ts
- src/SymbolTable.ts
- src/bscPlugin/validation/BrsFileValidator.ts
There was an issue with namespaces having multiple symbol tables for each time they were created. This fixes that by building a SINGLE namespacetype at the scope level and adding the aggregate namespace symbol table as a sibling.
> Fixes issue with multiple namespace symbol tables

- src/CacheVerifier.ts
- src/Program.ts
- src/Scope.spec.ts
- src/SymbolTable.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/types/ReferenceType.ts
- src/types/UnionType.ts
- Fixes when a Class is a Property of another class, and being unable to resolve it
- Fixes issue with Consts value looking at a `typetime` value of the RHS
- Does a better job of caching symbol lookups on memberTables
> Fixes some issues related to Classes as Properties and Consts validation

- docs/interfaces.md
- scripts/compile-doc-examples.ts
Adds baseline docs page for `interface`.
> Add baseline interface docs

- src/DiagnosticCollection.spec.ts
- src/DiagnosticCollection.ts
Prevent another crash when diagnostics are missing the `range` property.
> Prevent crashing when diagnostic is missing range.

- package-lock.json
- package.json
- src/cli.ts
Adds the ability to generate a profiler report from the brighterscript CLI by passing `--profile`.
Example:
```bash
bsc --project ./bsconfig.json --profile
```
> Add profiling support to the cli

- benchmarks/package-lock.json
- src/SymbolTable.ts
Makes use of parent and sibling type caches on `SymbolTable.getSymbolType` method calls.
Doesn't seem to make much difference on validate, though.
```
validate@local  ---------- 40.307 ops/sec
validate@0.65.1 --------- 103.031 ops/sec
```
> Better symbol table type retrieval - uses parent and sibling caches

- src/Program.ts
I was facing a bug where components were not ready by scope creation.
Also another issue is the dependency graph is not set yet before registering the component.
This makes the scope ready when the event is fired
> Make component ready on afterScopeCreate

- docs/plugins.md
- src/Program.spec.ts
- src/Program.ts
- src/interfaces.ts
Adding this event to give plugins a chance for clean up, even in the event of failure (especially in the event of failure)
> Add beforeProgramDispose event

- src/DiagnosticMessages.ts
- src/Scope.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/types/ObjectType.ts
Adds Function Call Type Validation when `enableTypeValidation` is `true`
- new method `ScopeValidator.validateFunctionCalls()` is called when `enableTypeValidation` is `true`
- Uses `Expression.getType()` to get the types of a function's arguments
- Validates against the function's parameters using the `BscType.isTypeCompatible()` methods
- When `enableTypeValidation` is `true` parameter count mismatches are also handled in new method instead of in `Scope.ts`
- Adds new spec file `ScopeValidator.spec.ts`
> Adds Function Call Type Validation

- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/parser/Statement.ts
- src/types/EnumType.ts
- src/types/StringType.ts
Fixes issue with enums not being properly treated as their underlying types when passed to functions.
> Support passing enums as their literal values

- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/types/BooleanType.ts
- src/types/ClassType.ts
- src/types/DoubleType.ts
- src/types/EnumType.ts
- src/types/FloatType.ts
- src/types/FunctionType.ts
- src/types/IntegerType.ts
- src/types/InterfaceType.ts
- src/types/InvalidType.ts
- src/types/LongIntegerType.ts
- src/types/StringType.ts
- src/types/UnionType.ts
- src/types/VoidType.ts
Fixes issue with `as object` types of variables, they need to be allowed to be passed to any function type (just like `dynamic`).
> Object type wider support

- package-lock.json
- package.json
- src/cli.ts
#833 added the ability to run a profiling session with a single cli flag. However, it also brought with it a dependency on `v8-profiler-next`, which requires node-gyp to compile. That's a pain. 
Since most bsc users won't be profiling the project, this PR moves that behind an on-demand install instead. That should help with nodejs compatibility and reduce npm install issues related to node-gyp.
> Install `v8-profiler-next` on demand instead of being a dependency

- src/parser/Parser.spec.ts
- src/parser/Parser.ts
> Type casts are not allowed in BrightScript

- src/diagnosticUtils.spec.ts
- src/diagnosticUtils.ts
- src/testHelpers.spec.ts
Normalize tab and spaces when printing diagnostics to the console. 
Example:
for this line:
`\t\tdescription = description.left(description.len() - 2) + "]"`
Turns this:
into this:
> Fix tab issue when printing diagnostics

- package-lock.json
- src/ProgramBuilder.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/diagnosticUtils.spec.ts
- src/diagnosticUtils.ts
- src/testHelpers.spec.ts
Print the `relatedInfo` portion of diagnostics.
> Print diagnostic related information

- src/Program.spec.ts
- src/Program.ts
Sort files prior to transpilation to ensure consistency between builds with regards to insertion of bslib.brs reference in transpiled XML files.
> ensure consistent insertion of bslib.brs

- src/bscPlugin/CallExpressionInfo.ts
The call expression could be be a callfunc, so the types reflect this
> Fixes types on call expression info class

- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.spec.ts
- src/parser/tests/statement/Enum.spec.ts
- Validates actual return type vs. the declared return type
- Subs and void functions will have validation errors when an actual type is included
- works in Brs and Bs files
https://github.com/rokucommunity/brighterscript/assets/810290/d065c1ee-30f2-496f-ad4d-2e66182b166b
> Adds Return type validation

- README.md
- src/BsConfig.ts
- src/Program.spec.ts
- src/Program.ts
- src/util.spec.ts
- src/util.ts
- Add `bslibDestinationDir` option.
- Update README to document new option.
- Add tests.
> allow optionally specifying bslib destination directory

- src/astUtils/creators.ts
- src/astUtils/reflection.spec.ts
- src/lexer/Lexer.spec.ts
- src/lexer/Lexer.ts
- src/lexer/Token.ts
- src/lexer/TokenKind.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/Parser.spec.ts
- src/parser/tests/controlFlow/For.spec.ts
- src/parser/tests/controlFlow/ForEach.spec.ts
- src/parser/tests/controlFlow/While.spec.ts
- src/parser/tests/expression/Call.spec.ts
- src/parser/tests/statement/PrintStatement.spec.ts
- src/parser/tests/statement/ReturnStatement.spec.ts
- src/parser/tests/statement/Set.spec.ts
- src/util.ts
Usefully as a way to get comments from expressions/statements
- Function, class, method, field, interface, namespace statements return valid data from `getLeadingTrivia()` function
- works with annotations as well
> Adds Leading Trivia to all tokens

- README.md
- src/BsConfig.ts
Add missing `emitDefinitions` entry in the readme.
Fix incorrect default `true` value for `emitDefinitions` in the `BsConfig` interface jsdocs comment
> Add missing emitDefinitions to docs and fix iface

- src/astUtils/creators.ts
- src/astUtils/reflection.spec.ts
- src/astUtils/reflection.ts
Fix `isLiteralInvalid` method to properly detect the true case. 
Add other `isLiteral*` methods.
Add unit tests for these methods.
> Fix isLiteralInvalid

- src/ProgramBuilder.ts
- src/Scope.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/diagnosticUtils.ts
- src/files/BrsFile.Class.spec.ts
- src/util.ts
Make the multi-scope diagnostic messaging for related infos more relevant (and concise). Also truncate that list since seeing 95 related infos is just noise...
Here's how it looks now:
> Better multi scope messages

- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/parser/tests/statement/ConstStatement.spec.ts
- src/parser/tests/statement/Enum.spec.ts
Fix a bug transpiling UnaryExpression when referencing namespaces and consts.
**Source:**
```brighterscript
const foo = 1
sub main()
bar = -foo
end sub
```
***transpiles to: BEFORE***
```brighterscript
sub main()
bar = -foo 'oops, that should be 1
end sub
```
***transpiles to: AFTER***
```brighterscript
sub main()
bar = - 1
end sub
```
> Fix UnaryExpression transpile for ns and const

- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
> Fixes Typed Arrays to allow Native Components

- src/lexer/Lexer.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
Fixes a token location bug in the template string lexer logic where the closing `}` had incorrect end char position.
> Fix incorrect quasi location in template string

- docs/plugins.md
This adds some additional information on plugins. If the note on the diagnostics availability in early build steps is too much detail I can remove it.
> Add some more details to the plugins docs

- src/util.spec.ts
- src/util.ts
fixes bug in `--noproject` logic that was skipping bsconfig loading sometimes when it shouldn't.
> fix bug in --noproject flag logic

- docs/interfaces.md
- src/parser/Parser.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
Adds support for function parameters in interface declarations. I had added this to v0.66, but it really should be in mainline since it's such a simple change.
> Add function parameter support in interfaces

- src/DiagnosticMessages.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/types/ArrayType.spec.ts
- src/types/ArrayType.ts
- src/types/AssociativeArrayType.ts
- src/types/BooleanType.ts
- src/types/BscType.ts
- src/types/DoubleType.ts
- src/types/FloatType.ts
- src/types/IntegerType.ts
- src/types/InterfaceType.spec.ts
- src/types/InterfaceType.ts
- src/types/LongIntegerType.ts
- src/types/StringType.ts
- src/types/helpers.ts
Also fixes type compatibility for `string` -> `roString`, etc.
`roArray` is basically the same as `dynamic[]`
> Fixes compatibility of built in types (roArray -> typed arrays)

- src/astUtils/reflection.ts
- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
- src/lexer/TokenKind.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/types/StringType.ts
Semantic tokens for Components Types/Interfaces:
Code completion in Type Cast/Type Expression:
> Semantic Tokes for Native Components and Type completion in Type Expressions

- scripts/scrape-roku-docs.ts
- src/roku-types/data.json
- src/types/BuiltInInterfaceAdder.ts
- src/types/UnionType.ts
If there are multiple overloads of a method in a BrightScript interface, it can be overriden in code so that there is a single definition of the method that can be added to the type system.
Fixes #926
> Allows `scrape-roku-docs` to consolidate overloaded methods

- src/parser/Parser.spec.ts
- src/parser/Parser.ts
Before:
`not myString = ""` -> `BinaryExpression<=>(UnaryExpression<not>(myString), "")` 
Now:
`not myString = ""` -> `UnaryExpression<not>(BinaryExpression<=>(myString, ""))` 
Fixes #898
> Fixes operator order for `not` keyword

- src/files/BrsFile.Class.spec.ts
- src/parser/Statement.ts
if there was a class field that used a constructor, the constructor was not namespaced correctly in the transpilation. This fixes that issue.
> Fix class fields using constructors not transpiling correctly

- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/tests/expression/UnaryExpression.spec.ts
- src/parser/tests/statement/ConstStatement.spec.ts
Fixes precedence in UnaryExpression parsing. 
ported from brs fix: https://github.com/rokucommunity/brs/pull/24
> Fix issue with unary expression parsing

- src/util.ts
Cache the range and position objects since they're immutable. This helps reduce memory footprint and garbage collection church. Also after a range has been created at least once, it should theoretically cost less CPU cycles since we just look it up from the cache instead of building a new one. 
For a large private project:
```
location cache: DISABLED 
build: (8s191.958ms) (7s967.413ms) (8s222.454ms) (8s035.043ms) | (avg: 8.104217seconds)
watch: (8s103.313ms) (8s104.476ms) (8s200.875ms) (8s100.466ms) | (avg: 8.127283seconds)
location cache: ENABLED
build:  (7s965.510ms) (7s977.796ms) (8s167.780ms) (7s960.608ms) (avg: 7.7679235seconds)
watch:  (7s873.529ms) (7s967.520ms) (8s018.557ms) (8s091.832ms) (avg: 7.9878595seconds)
```
For the same project, we end up caching a _ton_ of ranges and …
> Cache range and position

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Add fixes for the "go to definition" logic so that it finds classes and interfaces. 
Here's it working in action!
> Better go to definition support

- src/bscPlugin/transpile/BrsFileTranspileProcessor.ts
- src/files/BrsFile.Class.spec.ts
Previously, there was a transpilation bug when using enums directly (eg. with no namespace prefix) inside a namespace... I was seeing it especially in classes.
```
namespace MyNS
class HasEnumKlass
enumValue = MyEnum.A
end class
enum MyEnum
A = "A"
B = "B"
end enum
end namespace
```
was being transpiled to (notice the MyEnum.A):
```
function __MyNS_HasEnumKlass_builder()
instance = {}
instance.new = sub()
m.enumValue = MyEnum.A
end sub
return instance
end function
function MyNS_HasEnumKlass()
instance = __MyNS_HasEnumKlass_builder()
instance.new()
return instance
end function
```
> Fixes Transpilation bug - enums as class initial values

- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/files/BrsFile.Class.spec.ts
Same as https://github.com/rokucommunity/brighterscript/pull/949 , but for `master`
> Enums as class initial values

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/Program.ts
- src/Scope.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Previously:
```
for each scope file is in
on file text completion,
for each scope the file is in
get all symbols from entire symbol table
```        
Now:
```
on file text completion,
get symbols local to the completion position
for each scope the file was in
get symbols available at scope level
get symbols based on namespace inclusion
get the symbols from global scope
remove duplicates of same completion across different projects
```
> Completion performance

- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
In order to maintain a little bit of backwards compatibility, moves the `optional` token to the end for `InterfaceMethodStatement`, `InterfaceFieldStatement`, and `FieldStatement`.
> Fix param order for AST class constructors for interface/class members 

- src/types/BscType.ts
- src/types/InterfaceType.spec.ts
Fix a few crashes in the type system when an incoming type is `undefined`
> Fix crash in type system when an incoming type is `undefined`

- src/Scope.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/parser/Statement.ts
- src/parser/tests/statement/Enum.spec.ts
Fixes a critical transpile bug where non-namespaced enums used in namespaced function blocks would be left untranspiled!
> Fix transpile for non-namespaced enums in namespaced functions

- src/Scope.spec.ts
- src/Scope.ts
Fixes false diagnostics pertaining to interface and class statements for names that are a substring of a sub-part of a namespace.
> Namespace validation fix

- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
Fixes #986
Roku doesn't like when parens are used just to wrap a variable, for example, this will cause a run-time error:
```brs
sub addSomeProperty(obj)
(obj).append({key: "value"})
end sub
```
this causes a problem when we want to typecast a single variable in order to code completion, for example:
```brs
sub addSomeProperty(obj)
(obj as roAssociativeArray).append({key: "value"})
end sub
```
This PR changes `GroupedExpression` so that if the expression that is grouped is a typecast, it does not include the parens.
> Fixes transpiles of Typecasts wrapped in parens

- src/AstValidationSegmenter.ts
- src/DiagnosticMessages.ts
- src/SymbolTable.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/util.spec.ts
- Adds diagnostics for setting unknown fields of classes
- Adds diagnostics for accessing `private` or `protected` class members when you shouldn't have access to them.
Private members are available in the class that defined them
Protected members are available in the class that defined them, and all sub classes.
https://github.com/rokucommunity/brighterscript/assets/810290/bcb37181-ea2f-4f7f-8892-47e4105ca37a
Solves #966 
Solves #967 
Solves #918
> Adds Diagnostics for Member Accessibility 

- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
There's a small bug where the ProgramBuilder doesn't have a reference to .program when the afterProgramCreate. This solves that by assigning `.program` before emitting the event.
> Assign `.program` to the builder BEFORE emitting `afterProgramCreate` event

- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- Adds `true` `false` and `invalid` when appropriate
- Ensures function parameters are included in completion results, even if you're at the end of the function block
- `private` and `protected` class members only are included in completion results when they are accessible
solves #988
> Adds missing Completion Items

- README.md
Adds documentation on the new `pruneEmptyCodeFiles` bsconfig option to the README.
The bsconfig section of the README is a little long. Would you prefer that it get moved under the docs folder, maybe just leaving the shell of the most minimal `bsconfig.json` file on the main README?
> add documentation on pruneEmptyCodeFiles to the README

- src/Program.spec.ts
- src/XmlScope.spec.ts
- src/util.ts
Includes all the fields types as defined here: https://developer.roku.com/en-ca/docs/references/scenegraph/xml-elements/interface.md#attributes
Fixes (in particular) the `type="array"` isse @georgejecook has.
> Updates the Member types for Component Fields

- src/Program.spec.ts
- src/files/BrsFile.spec.ts
- src/util.spec.ts
- src/util.ts
We found that component libraries that use libpkg:/path/file.brs in the script imports would result in files not being found.
This pr adds support for both pkg types.
> adds support for libpkg prefix

- src/Scope.spec.ts
- src/Scope.ts
Fixes a bug where a const and a function are not allowed to have the same name across different namespaces.
> Fix cross namespace collision detection

- src/CommentFlagProcessor.ts
- src/DiagnosticCollection.spec.ts
- src/LanguageServer.spec.ts
- src/Program.ts
- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/Scope.ts
- src/XmlScope.ts
- src/astUtils/reflection.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/AssetFile.ts
- src/files/BrsFile.ts
- src/files/BscFile.ts
- src/files/XmlFile.ts
- src/index.ts
- src/interfaces.ts
- src/testHelpers.spec.ts
- src/validators/ClassValidator.ts
Resolves #1005 
Renames `File` interface to `BscFile` and removes the `BscFile` type. This is so this project does not clash with the Javascript `File` type.
> Renamed `File` interface to `BscFile`

- src/Program.ts
- src/ProgramBuilder.ts
Some plugins might want to load the manifest and preprocess it before the program gets to it. However, sometimes there are timing issues, so now we don't replace the manifest on startup if a plugin has already overwritten it.
> Prevent overwriting the Program._manifest if already set on startup

- src/Program.spec.ts
- src/Program.ts
- src/types/BuiltInInterfaceAdder.ts
Adds all the interfaces a built-in object has as accessible members.
addresses: #1038
> Built-in Objects have their interfaces as members

- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
We agreed that since AAs can change and have their properties overwritten, there will be no validation on invalid types on dotted-set's and dotted-gets of AAs
Addresses #1037
> Do not do validation on dotted sets of AAs

- bsconfig.schema.json
- src/BsConfig.ts
- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/util.ts
New `bsconfig.json` option:
```
"legacyCallfuncHandling": {
"description": "Legacy RokuOS versions required at least a single argument in callfunc() invocations. Previous brighterscript versions handled this by inserting invalid as an argument when no other args are present. This is not necessary in modern RokuOS versions.",
"type": "boolean",
"default": false
}
```
addresses #1018
> Changed adding invalid as arg to empty callfunc invocations by default

- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/expression/Indexing.spec.ts
Fixes parsing and transpile issues with mutli-index `IndexedGetExpression` and `IndexedSetStatement`.
The solution is a little "icky", because we can't break backwards compatability, so I had to add `additionalIndexes` to the two AST node types. In v1, we should merge those into a single `.indexes` prop on the nodes instead. 
Fixes #1048
> Fix parsing issues with multi-index IndexedSet and IndexedGet

- src/astUtils/reflection.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/expression/Indexing.spec.ts
#1050 fixed the indexedGet and indexedSet AST parsing in a backwards compatible way (`additionalIndexes`). But this PR refactors that in a breaking way for v1 into a single prop called `.indexes`.
> Indexed get set multi index

- src/files/BrsFile.spec.ts
- src/parser/Parser.ts
- src/validators/ClassValidator.ts
Allows without diagnostic, but no deeper validation:
- built-in types for class member types
- type declarations on LHS of assignments
eg. this is now ok:
```
class Foo
node as roSGNode
end class
sub someFunc()
myStr as string = "hello"
end sub
```
> Allow Additional v1 Syntax:

- src/Scope.spec.ts
- src/Scope.ts
This fixes an issue in the JellyFin-roku project
The issue was that it was using the `roku-log` which declares the namespace `log`.
Previously, this was a problem because it shadows the native function `log`, and `Scope.linkSymbolTable()` panicked when the type of something that should have been a namespace wasn't a namespace, and quit processing the rest of the namespaces.
Anyway, that's fixed in this PR. More work needs to be done to handle *general* shadowing, but this fixes the specific issue for Jellyfin-roku
> If a namespace shadows a function, still allow processing to continue

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- Adds the `file` prop to sourcemaps to better align with the spec.
- fixes the filename in the sourceMappingUrl comment at the bottom of every file
- moves the sourceMappingUrl entry to a new line to make the file more clean
> Fix sourcemap comment and add `file` prop to map

- docs/plugins.md
- src/Program.ts
- src/bscPlugin/BscPlugin.ts
- src/bscPlugin/references/ReferencesProvider.spec.ts
- src/bscPlugin/references/ReferencesProvider.ts
- src/files/BrsFile.ts
- src/interfaces.ts
Add support for plugins to contribute `references` when running as part of a language server.
> Add support for `provideReferences` in plugins

- docs/plugins.md
- src/interfaces.ts
Simplify the plugin method signatures so that plugins get better code help when autocompleting new plugin events. 
Before: 
```typescript
beforeProgramCreate?: PluginHandler<BeforeProgramCreateEvent>;
```
After:
```typescript
beforeProgramCreate?(event: BeforeProgramCreateEvent): any;
```
Fixes #1022
> Simplify the plugin method signatures.

- src/astUtils/reflection.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/hover/HoverProcessor.ts
Fixes: #907
Enums members
Class Members (looks same as interfaces):
> Fix member hovers for classes, interfaces and enums

- src/Scope.ts
- src/astUtils/CachedLookups.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.Class.spec.ts
- src/validators/ClassValidator.ts
Previously, the check for this was in `ClassValidator` and only checked for `new` with callables. It was moved to `ScopeValidator`, and made more general, so it catches ALL uses of `new` on non-classes
As a result, `CachedLookups.newExpressions` was not used anymore, so it was removed.
> Adds validation for calling `new` on a non-class constructor

- src/parser/Parser.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
Fixes a bug where empty interfaces would break the parser
> Empty interfaces break the parser

- src/bscPlugin/hover/HoverProcessor.ts
- src/files/BrsFile.ts
- src/files/XmlFile.ts
- src/interfaces.ts
- src/parser/AstNode.ts
- src/parser/BrsTranspileState.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
- src/util.ts
This fixes most of the null safety issues in Statements and Expressions. I left a few that seemed like they'd be disruptive to modify.
The largest changes were widening the type of `TranspileResult` to be a tree rather than a flat array, and wrapping constructions of `SourceNode` in a helper which does a type coercion.
Most of the changes were setting the `Range` field to be optional everywhere and adding manual type annotations to the `result` variable in `transpile` methods, to avoid issues with `never[]` being inferred as a type.
Please let me know if any of these changes cause excessive merge conflicts and I can back them out.
> Reduce null safety issues in Statement and Expression subclasses

- docs/bsconfig.md
- src/DiagnosticFilterer.spec.ts
- src/DiagnosticFilterer.ts
This feature lets users prefix a glob with `!` to make it a negative pattern which un-ignores certain errors. My use case for this is one which I've added to the documentation; I want to ignore errors from all dependencies in a project _except_ for one specific dependency, and I don't want to have to maintain a list of all other dependencies any time one is added or moved.
Using file paths to indicate un-ignores means that it's not possible to un-ignore a code without specifying a file path. A workaround for this is to use the glob `!*/**/*`, matching everything in the rootDir. I've added this to the documentation and the tests.
The implementation is such that it's possible to un-un-un-un-ignore patterns to any depth. This is likely overkill and would be inadvisable to do in practice, but …
> Allow negative patterns in diagnostic filters

- package-lock.json
- package.json
- scripts/create-test-package.ts
Adds a new package.json command called `create-test-package` that generates a .tgz npm package that can be used for testing the current brighterscript code. It also copies the install command to the clipboard so it's easier to run in the project you want to test. 
It copies this to clipboard:
```bash
npm i file:c:/projects/roku/brighterscript1/.tmp/brighterscript-0.65.24-test.1709734928445.tgz
```
> Add `create-test-package` command for easier tgz testing

- package-lock.json
- src/astUtils/creators.spec.ts
- src/astUtils/creators.ts
- src/astUtils/reflection.spec.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/lexer/Lexer.ts
- src/lexer/Token.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/Parser.spec.ts
- src/preprocessor/Chunk.ts
- src/preprocessor/PreprocessorParser.ts
- src/testHelpers.spec.ts
- src/util.ts
Many plugins use `Parser.parse()` to generate AST used to replace existing code. This causes the generated sourcemaps to be very incorrect. To mitigate this, we should support generating AST without any range information at all. But, lots of our codebase explodes when that happens. 
This PR adds a test that verifies _most_ expressions and statements  can transpile to proper code without needing tokens. There may be some edge cases, but we've tried to hit as many as possible.
Here's how you can leverage this new functionality:
```typescript
const tokens = Parser.parse('print hello', { trackLocations: false });
```
The tokens array will have all the same tokens, but none of them will have location information, making them much safer to inject into AST without messing with sourcemaps.
> Support when tokens have null ranges

- src/index.ts
Add back in the missing `SymbolTypeFlag` interface so plugins can use it.
> Export symbol type flag

- src/Scope.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.spec.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
- src/parser/tests/statement/ConstStatement.spec.ts
- src/types/BscType.ts
- src/util.ts
https://github.com/rokucommunity/brighterscript/assets/810290/96313697-7232-4e9e-bdc3-60876fc83783
When a Class constructor function is used outside of `new` it is treated as a function type, allowing code completion and validation based on that.
This PR also adds member (and method) validation on primitive types in general
> Fix classname as variable for completions and validations

- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
- transpiles empty throw with "User-specified exception"
- addresses #1086
> Improves message for empty throw statements

- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/parser/Expression.ts
- src/types/AssociativeArrayType.ts
Fixes #1102
AssociativeArray types now follow the same pattern as Class Types, where the built in members are from a different symbol provider, so if they are overriden, the overriden type info is used.
> Fixes issue with AA overriding built-in properties

- src/parser/Expression.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
- src/util.ts
Prevents unused variable warnings when transpiling ternary and null coalescence expressions if they include enums and constants.
Addresses: #1091
> Prevent unused variable warnings on ternary and null coalescence expressions

- src/files/BrsFile.spec.ts
- src/parser/TranspileState.ts
- src/testHelpers.spec.ts
Fix crash in during transpile when token is defined but doesn't have `text` (no idea how this happens, but better to prevent crashing)
> Fix transpile crash when token has no text

- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
Increases the max number of function parameters from 32 to 63, which seems to have been implemented in the Roku OS since OS 11.5 and above
**Before:**
**After:**
> Increase max param count to 63

- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/types/ReferenceType.spec.ts
- src/types/ReferenceType.ts
Needed to add a whole new ReferenceType for this use case!
Because the for-each-loop target was defined on a namespace, it wasn't defined yet at File-validation time (Namespaces are only defined at scope linking), so the default type was unknown.
Now that we have a reference type for this particular case, the array symbol can be defined in the future, and the for-each item will be automatically known.
> Added ArrayDefaultTypeReferenceType for when array symbol is not defined yet

- benchmarks/package-lock.json
- src/AstValidationSegmenter.ts
- src/Scope.spec.ts
- src/Scope.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
Refactors local variable checking to only check un-changed `AstSegment`s for function shadowing if those segments make an assignment to a symbol that changed.
Before:
```
validate@local   ---------- 51.368 ops/sec
validate@0.65.26 --------- 101.435 ops/sec
```
After: 
```
validate@local   --------- 286.331 ops/sec
validate@0.65.26 --------- 102.877 ops/sec
```
> More validation performance

- src/files/BrsFile.spec.ts
- src/util.ts
Fixes an issue in `util.createRange()` and `util.createPosition()` where integers over 13 bits long would sometimes generate an incorrect cache key (thus returning the wrong cached value and wrong position/range values).
> Fix bug in range and position caching

- src/Scope.spec.ts
- src/types/InheritableType.ts
Look ma, no diagnostics:
```
program.setFile<BrsFile>('source/aa.bs', `
sub foo(someAA as roAssociativeArray)
print someAA.whatever.whatever
end sub
`);
program.validate();
expectZeroDiagnostics(program);
```
> Removes diagnostic on accessing unknown member of roAssociativeArray

- docs/readme.md
- docs/typecasts.md
- src/DiagnosticMessages.ts
- src/astUtils/CachedLookups.ts
- src/astUtils/reflection.ts
- src/astUtils/visitors.ts
- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/lexer/TokenKind.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Adds ability to add a single statement to beginning of file or function, and every usage of `m` in that or lower scopes will be typecast as the type given.
Syntax: 
```
typecast m as <type>
```
eg:
```
import "types.bs"
typecast m as Thing1
sub func1()
x = m.value ' x is type of Thing1.value
print x
end sub
sub func2()
typecast m as Thing2 
x = m.value  ' x is type of Thing2.value
print x
end sub
sub func3()
aa = {
innerFunc: sub()
typecast m as Thing3
x = m.value  ' x is type of Thing3.value
print x
end sub
}
end sub
class TestKlass
value as string
sub method1()
x = m.value ' x is type of TestKlass.value
print x
end sub
sub method2()
typecast m as Thing1
x = m.value  ' x is type of Thing1.value
print x
end sub
end class
```
> Adds `typecast m as <Type>` statement

- docs/typecasts.md
- src/Scope.spec.ts
- src/SymbolTable.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.ts
- src/interfaces.ts
In namespace statement with typecast:
in sibling namespace statement without typecast:
> Typecast symbols are not merged to other namespaces

- src/util.ts
Turns out #940 actually slowed down performance. It's faster to just make new `Range` and `Location` objects directly. V8 does a great job optimizing this flow.
Caching enabled on `local`:
Caching disabled on `local`:
> Revert range and column caching

- src/files/XmlFile.spec.ts
- src/parser/SGTypes.ts
There was an issue in XML transpilation where self-closed elements that later had child elements added to them would not have those child elements transpiled.
Fixes #1146
> Fixes includes in self closing components

- src/util.spec.ts
- src/util.ts
fix: resolve the stagingDir option relative to the bsconfig.json file
Resolve `stagingDir` relative to the `bsconfig.json` file similar to the other paths. 
⚠️ This is a breaking change in behaviour of the bsconfig.json.
solves https://github.com/rokucommunity/brighterscript/issues/1141
given the below two config files
1. **./node_modules/shared-config/bsconfig.json**
```json
"rootDir": "../../src",
"stagingDir": "../../build"
```
2. **./bsconfig.json**
```json
{
"extends": "./node_modules/shared-config/bsconfig.json",
}
```
**Expected result:**
```terminal 
$ rootDir: {cwd-dir}/src
$ stagingDir: {cwd-dir}/build
```
unit test
> fix: resolve the stagingDir option relative to the bsconfig.json file

- scripts/scrape-roku-docs.ts
- src/Program.spec.ts
- src/roku-types/data.json
Types would get messed up if there were duplicate definitions of members.
This could happen from the scraper.
This pr fixes the scraper so that it fixes all the overloaded methods in interfaces automatically.
fixes: #1162 
these are all the overloads the scraper fixed automatically on last run:
```
Fixed overloaded method ifAudioResource.trigger
Fixed overloaded method ifByteArray.writefile
Fixed overloaded method ifByteArray.readfile
Fixed overloaded method ifByteArray.appendfile
Fixed overloaded method ifByteArray.getcrc32
Fixed overloaded method ifDateTime.toisostring
Fixed overloaded method ifDraw2D.drawscaledobject
Fixed overloaded method ifFontRegistry.getdefaultfont
Fixed overloaded method ifSGNodeField.observefield
Fixed overloaded method ifSGNodeField.observefieldscoped
Fixed …
```
> Fix roDateTime compatibility issue

- src/Scope.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/hover/HoverProcessor.ts
Previously, the type displayed on an assignment was the type of the RHS expression.
This changes that so it does a symbolTable lookup for the token on the LHS.
Symbol table type lookups return a union type of all assigned types for that symbol.
It is bad code style to use the same variable name for different types! We need to add that to BSLint.
> Hovers on LHS of assignments do symbol type lookups

- src/DiagnosticMessages.ts
- src/Program.spec.ts
- src/Scope.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.spec.ts
- src/files/tests/imports.spec.ts
Moves "cannot find name" diagnostics for function calls into their own diagnostic code. This will help dev teams more slowly migrate to "best practices" in their projects by ignoring this specific diagnostic when functions are imported into only some of the scopes the script is used in. 
**Before:**
**After:**
> Move function calls to separate diagnostic

- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/Scope.ts
- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/hover/HoverProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.Class.spec.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/types/UnionType.ts
- src/util.ts
- Adds extra detail to `cannotFindName` diagnostic to say what it cannot find the name in
- If a union type is in a Brighterscript file, it will act like a Dynamic type
- Removes functionExpression body symbol table, in favor of single symbol table that also includes the params. (I think this solves #1167)
> Fixes union type issues with unknown members

- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
- src/files/BrsFile.ts
Fix a crash when a diagnostic is trying to be printed, but has no range.
> Fix crash when diagnostic is missing range

- src/astUtils/visitors.spec.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
Solves #1181 
This allows access to the trivia at the end of a block when walking the AST
> Adds `AstNode.getEndTrivia()`

- src/DiagnosticManager.ts
adds:
```
public register(diagnostics: Array<BsDiagnostic>, context?: DiagnosticContext);
```
useful for adding a bunch of diagnostics, all having the same context
> Added extra DiagnosticManager.register() overload

- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
- src/parser/tests/statement/InterfaceStatement.spec.ts
Fixes:
- leading comments before `alias`, `typecast`, and `import` statements
- comments on same line as previous statement before `namespace`
> Fixes some issues with comments and transpilation

- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
Addresses #1191 
Changes `assignementTypeMismatch` validation so that if LHS is a DottedSetStatement, and the `obj` is a ComponentType (ie. a SG Node), and RHS is a string, then do not show the validation diagnostic.
> Component field can be set with strings

- src/SemanticTokenUtils.spec.ts
- src/SemanticTokenUtils.ts
- src/util.ts
Exclude semantic tokens that have no range (we wouldn't know where to colorize anyway...)
> Fix semantic token crash

- src/astUtils/Editor.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Fix crash when trying to transpile a function on an unknown namespace.
> Fix namespace crash

- .github/workflows/build.yml
Disable the `test-related-projects` job until those projects support v1. These jobs currently take a long time because they're all failing with thousands of errors due to v1 incompatibility.
> Temporarily disable test-related-projects until they support v1

- src/astUtils/visitors.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/testHelpers.spec.ts
- src/util.spec.ts
- src/util.ts
Removes the `startingRange` property on Blocks.
If a block is not empty, the range of a Block is the range of its statements
If the block is empty, the Block looks at its parent to see what the range should be, with specific logic for all the different types of nodes that can contain a block.
> Remove block starting range

- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/controlFlow/If.spec.ts
- src/testHelpers.spec.ts
- It was changed to a getter, so that proper diagnostic could still be added if there was a problem.
- Added tests for inline conditional statements
- Added support for nested inline conditionals. (People must have a deathwish!)
> Removed `isInline` property from `IfStatement` 

- src/bscPlugin/SignatureHelpUtil.ts
- src/lexer/Lexer.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Statement.spec.ts
- src/parser/Statement.ts
- src/util.spec.ts
- src/util.ts
- All AstNodes will return an editable array of tokens when calling `.getLeadingTrivia()`
- No longer concatenates leading trivia of annotations above a statement
- Refined utils functions that get node documentation to ensure all comments are included, and these concatenate leading trivia of associated annotations 
Addresses #1206
> Allow updating leading trivia

- src/astUtils/visitors.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.spec.ts
- src/parser/Statement.spec.ts
- src/parser/Statement.ts
- src/util.ts
- Changed `AstNode.getLeadingTrivia()` to `AstNode.leadingTrivia`
- Changed `getEndTrivia()` as well
- Added Tests to verify comments (and changed comments) appear in transpiled output
> Made `AstNode.getLeadingTrivia()` a getter

- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
There was a bug that if a file was in multiple scopes, global completions and completions for the same file were only included once, that is not for every scope. However, there's also a process that filters out completions that don't work for every scope.
This is not the most performant code, because it has to link every scope, as well as do symbol tables checks for every scope, but it works.
Addresses: #1235
> Fixes completions when file in multiple scopes

- src/bscPlugin/completions/CompletionsProcessor.ts
Sets a hard limit (of 5) of the number of scopes to check for a file when processing completions.
In Jellyfin, completion processing went from ~500ms to ~9ms
Fixes #1240
Based off code found in this commit: https://github.com/rokucommunity/brighterscript/commit/bac0ae90bcc00df2689371e451983c33478c4695
> Sets a hard limit of number of scopes to check for completions

- package-lock.json
- package.json
- src/DiagnosticCollection.ts
- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/ProgramBuilder.ts
- src/lsp/LspProject.ts
- src/lsp/PathFilterer.spec.ts
- src/lsp/PathFilterer.ts
- src/lsp/Project.ts
- src/lsp/ProjectManager.ts
- src/lsp/worker/WorkerThreadProject.ts
- src/testHelpers.spec.ts
- src/util.spec.ts
Fixes several issues related to standalone workspaces:
- We weren't properly destroying standalone workspaces when a different project handled that file, thus leaving diagnostics alive forever
- we weren't handling file and document changes for standalone workspaces, leaving the file in its initial state unless you close the file
- fix recovery issues when a bsconfig was loaded with invalid syntax (so open files load as standalone), but then the bsconfig.json was fixed....the files never got handed back to the main project.
> Fix standalone project issues

- src/files/BrsFile.Class.spec.ts
- src/parser/BrsTranspileState.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
Due to the change to remove `CommentStatement`, leading trivia transpilation is done automatically for each statement.
Since we need to rely on function transpilation, a new state flag was added to remove transpiling function leading comments.
those comments are now added *before* the function is added to the instance  
Fixes #1256
Thanks for the find, @iBicha
> Ensure methods leading comments are transpiled above instance function definition

- src/parser/Expression.spec.ts
- src/parser/Expression.ts
Adds support for simple templatestrings as arguments for annotations when calling .getArguments()
> Add templatestring support for annotation.getArguments()

- src/AstValidationSegmenter.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
Fixes #1265 
Conditional compilation blocks (like namespaces) have no symbols in and of themselves that require validation, so they are skipped.
> Ensures conditional compilation blocks have proper validation segments

- src/bscPlugin/completions/CompletionsProcessor.spec.ts
- src/bscPlugin/completions/CompletionsProcessor.ts
- src/util.ts
If the original file ends in `.bs` , use that instead of `.brs` in absolute imports
addresses: #1258
> Make absolute import completions use original extension

- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
Example:
```
class Test
sub method()
stub = function()
m.whatever = false ' m here is unknown - it is an AA
end function
end sub
end class
```
> `m` should be typed as roAssociativeArray for all inline functions

- src/files/BrsFile.spec.ts
- src/parser/BrsTranspileState.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
Fixes several issues where comments were being missed when transpiling. Specifically around annotations above statements, and namespaced function calls.
Fixes #1274
> Include missing transpiled comments

- src/Scope.spec.ts
- src/bscPlugin/transpile/BrsFileTranspileProcessor.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.Class.spec.ts
- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
- src/parser/Expression.ts
- src/util.ts
Addresses #1277 
Fixes transpilation issues with variables that shadow things in namespaces.
Basically, "closest thing wins"
If a variable or function param shadows a const, enum, etc. then it does not do any special transpilation, but instead uses it as-is.
However, there are still diagnostics for when a variable shadows a non-namespaced function or class, because using those still lead to un-defined behaviour.
eg:
```
sub foo()
end sub
sub bar()
foo = 1 ' this shadows the function above
print foo ' this could lead to un-defined behaviour
end sub
```
however, if the function or class IS in a namespace, then it’s okay, because the transpilation will change the name:
```
namespace alpha
sub foo()
end sub
sub bar()
foo = 1 
print foo
end sub
end namespace
```
transpiles to:
```
sub …
```
> Added tests and fixes around transpiling variables that shadow stuff

- src/DiagnosticCollection.ts
- src/DiagnosticManager.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
Fixes #1275
Also, if there was a BrsFile that was unscoped, like in `/components` but not included in a component, the Language server would crash in the semantic tokens parser when trying to link a scope
> Handles diagnostic with invalid location, and semantic tokens for unscoped file

- bsconfig.schema.json
- src/BsConfig.ts
- src/util.spec.ts
- src/util.ts
Add bsconfig value for resolving the `sourceRoot` at time of loading the config.
> Add support for resolving sourceRoot at time of config load

- src/DiagnosticManager.spec.ts
- src/DiagnosticManager.ts
- src/Program.spec.ts
- src/Program.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
Fix a few crashes related to diagnostics having null location or uri properties. No idea how these happen, but it's still better to not crash.
> Fix some null crashes

- package-lock.json
- package.json
- src/astUtils/reflection.ts
- src/astUtils/visitors.ts
- src/parser/AstNode.spec.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Statement.spec.ts
- src/parser/Statement.ts
- src/types/ArrayType.ts
- src/types/BooleanType.ts
- src/types/BscType.ts
- src/types/CustomType.ts
- src/types/DoubleType.ts
- src/types/DynamicType.ts
- src/types/FloatType.ts
- src/types/FunctionType.ts
- src/types/IntegerType.ts
- src/types/InterfaceType.ts
- src/types/InvalidType.ts
- src/types/LongIntegerType.ts
- src/types/ObjectType.ts
- src/types/StringType.ts
- src/types/UninitializedType.ts
- src/types/VoidType.ts
- src/util.ts
Add `.clone()` method to AstNode and BscType objects. This will make for much easier duplication of template code for plugins.
> Ast node clone

- docs/exceptions.md
- docs/readme.md
- src/DiagnosticMessages.ts
- src/astUtils/reflection.spec.ts
- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.spec.ts
- src/parser/Statement.ts
- src/parser/tests/statement/Throw.spec.ts
- src/parser/tests/statement/TryCatch.spec.ts
- src/testHelpers.spec.ts
Our current `CatchStatement` stores the exception variable as a `Token`. This PR converts the `CatchStatement.exceptionVariable` property to an `Expression`, which supports `VariableExpression` and `TypeCastExpression`. This should more closely align with how TypeScript supports `catch(e as <any type you want here>)`. This was a breaking change to the AST, so it needed to be done as part of v1.0.0
Also supports completely omitting the exception variable when you don't need to use it. 
```BrighterScript
function init()
try
somethingDangerous()
catch
print "I live on the edge"
end try
end function
```
transpiles to
```BrighterScript
function init()
try
somethingDangerous()
catch e ' or __bsc_error if there's a local variable conflict
print "I live on the edge"
end try
end function
```
> Support omitting exception variable in bs files and convert exception var to an Expression

- src/util.spec.ts
- src/util.ts
Prevent a runtime exception in the validator whenever `ClassType.name` is missing. I'm not sure how to reproduce this, but it's good enough to harden this code so it doesn't happen.
> Prevent crash for missing classtype name

- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.spec.ts
- src/bscPlugin/semanticTokens/BrsFileSemanticTokensProcessor.ts
Fix incorrect semantic token colorization for instances of components and interfaces. Since they're _instances_, they should be normal variable colors. 
Also fixes incorrect `m` colorization
**Before:**
**After (fixed):**
Fixes #1308
> Fix semantic tokens for components and interfaces, and m

- src/bscPlugin/serialize/FileSerializer.ts
- src/files/BrsFile.spec.ts
- src/util.ts
Fixes issue where use of global functions in a namespace would cause tranpilier to prefix the functions
fixes #1307 
Given:
```
namespace is
function node(thing) as boolean
return invalid <> getInterface(thing, "ifSgNodeChildren")
end function
end namespace
```
before would transpile to:
```
function is_node(thing) as boolean
return invalid <> is_getInterface(thing, "ifSgNodeChildren")
end function
```
now transpiles to:
```
function is_node(thing) as boolean
return invalid <> getInterface(thing, "ifSgNodeChildren")
end function
```
> Fixes transpile issue with global functions

- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
Fixes a crash when calling ProgramBuilder.run with undefined options.
> Prevent crash when ProgramBuilder.run called with no options

- docs/namespaces.md
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/Statement.ts
Fixes:
```brighterscript
namespace alpha
sub foo()
end sub
namespace beta
sub bar()
foo()  ' this SHOULD be a an error -- no function foo() at file scope.
end sub
end namespace
end namespace
```
From this slack conversation: https://rokudevelopers.slack.com/archives/CKF1QQGTY/p1728307032364379
> Fixes using upper namespaced function indirectly

- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.spec.ts
- src/testHelpers.spec.ts
If a function explicitly says it will return something, ensure there is a return statement.
This could be improved by checking all branches.
I know there's a BSLint option that basically checks the same thing, but if you don't have a return statement when you say you're going to return a string or an integer, it will crash.
> Adds diagnostic if no return statement found in function

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Fixes a bug with namespace-relative function calls when the file is a member of no scopes.
> Fix namespace-relative transpile bug for standalone file

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/lsp/PathFilterer.spec.ts
- src/lsp/PathFilterer.ts
Fixes bugs with the .gitignore entries in PathFilterer for the language server. There were several bugs in there:
- the `PathFilterer` wasn't registering the exclusion callbacks
- the gitignore function (called `ignore`) requires relative paths with no `../` or absolute paths, so we need to call `path.relative()` and exclude any paths not matched
> Fix issues with the .gitignore loading for pathFilterer

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
Fixes several issues related to the PathFilterer in the language server.
- Retain project-specific registrations whenever `rebuildPathFilterer` runs
> rebuildPathFilterer now retains project-specific patterns on rebuild

- src/XmlScope.spec.ts
- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/files/BrsFile.spec.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
This PR changes the parser so any custom type (eg. Class names, interfaces, built in types, etc) will result in a diagnostic:
`BrighterScript feature 'custom types' is not supported in standard BrightScript files`
Fixes: #1335
> Adds Parser error when custom type encountered in `brs` file

- src/BusyStatusTracker.spec.ts
- src/BusyStatusTracker.ts
- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/lsp/LspProject.ts
- src/lsp/Project.ts
- src/lsp/ProjectManager.ts
- src/lsp/worker/WorkerThreadProject.ts
Include more details in the busy status tracker, which will help visualize what's actively running when hovered in the editor.
> Include more details in the busy status tracker

- src/files/BrsFile.spec.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
For some expressions and statements, we can do a better job of assuming what some missing tokens will be.
This is useful for constructing AST nodes via code, so we don't need to specify tokens for open and close parens in a function call, for example.
Includes fixes for `CallExpression`, `PrintStatement` and `FunctionExpression`
Basically, anywhere there is a token where it HAS to be a certain character or string, we might as well put in a default for transpile time, so you don't need to include EVERY token in a constructor.
> Allows more missing tokens in Transpile

- docs/plugins.md
- docs/ternary-operator.md
- scripts/compile-doc-examples.ts
- src/astUtils/creators.ts
- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/TranspileState.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
Whenever a ternary expression is on the right-hand-side of an assignment, dottedSet, or indexedSet statement, we can transpile the entire thing to an `if` statement instead which improves performance significantly (should be identical to handwritten non-ternary code). 
This PR adds this `if` statement transpiling for all of the following situations:
- assignments: `a = true ? 1 : 2`
- dotted set: `m.a = true ? 1 : 2`
- indexed set: `m["a"] = true ? 1 : 2`
- complex assignment operators (i.e. `+=`, `-=`, etc...) `size += true ? 1 : 2`
- grouped ternaries: `a = (((true ? 1 : 2)))`
- nested ternaries `a = true ? (false ? 1 : 2) : 3`
These are explicit cases, so any situation other than these will be transpiled according to the existing rules …
> Optimize ternary transpilation for assignments

- .eslintrc.js
- package-lock.json
- package.json
- src/lsp/ProjectManager.spec.ts
- src/lsp/worker/MessageHandler.spec.ts
- src/lsp/worker/MessageHandler.ts
Fixes a bug in the language server rewrite where, if a project has a pending request (such as `getCompletions` or `validate`) and is disposed/destroyed before the request completes, the entire language server would hang indefinitely. 
This fixes the issue by keeping track of every outgoing request. If the project is disposed, then all of those pending request promises will be rejected.
> Reject pending project requests when disposed

- src/astUtils/visitors.spec.ts
- src/astUtils/visitors.ts
- src/parser/Statement.ts
Fix a bug that doesn't properly recover when the array being walked changes.
The core change in logic is as follows:
- during an AST walk, if the visitor returns a new node, we will not walk the original node's children, and instead walk the new node's children
- if a visitor changes an array (like `statements`), we will do a simple change detection method: `array[i] !== valuePassedToVisitor`. If we detect that it has changed, we'll restart the walk over that array (but skip any nodes we've already visited). This _can_ result in elements being visited out of order, but the use case for this is to help during transpile, so the order typically matters less.
> Fix issues with the ast walkArray function

- src/bscPlugin/transpile/BrsFilePreTranspileProcessor.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
Fixes #1356 . 
The issue was that we were only checking if the parent of the ternaryExpression was an IndexedSet, but we currently only support lifting the VALUE of those expressions, not their indexes. So this now guards against matching on the indexes.
> Fix bug with ternary transpile for indexed set

- src/index.ts
Adds a few additional exports from the vscode-languageserver package to eliminate the need for external projects to directly require that package.
> Add more convenience exports from vscode-languageserver

- src/BusyStatusTracker.spec.ts
- src/BusyStatusTracker.ts
Fix bug with the lsp busy spinner never stopping.
> Emit `active-runs-change` event _after_ removing it from the array.

- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
> Ensures diagnostic on using Variable from parent function in an inner function

- src/DiagnosticMessages.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
For everything but `string`, a function with no return statement will be coerced into the specified type.
Fixes #1334
> Changes `expectedReturnStatement` to `returnTypeCoercionMismatch` 

- src/Program.spec.ts
- src/Program.ts
- src/common/Sequencer.spec.ts
- src/common/Sequencer.ts
- src/lsp/Project.spec.ts
- src/testHelpers.spec.ts
Forces `validate()` to run one-at-a-time. This prevents race conditions with diagnostics not always being cleaned up correctly.
> Prevent simultaneous validate() for same project

- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/types/ArrayType.ts
- src/types/EnumType.ts
- src/types/ReferenceType.ts
- src/types/UnionType.ts
- src/types/helpers.ts
- src/util.ts
Fixes #1323 
Default values/initial values are much more stable, and support things like arrays of enum values:
> Fixes default type for ArrayLIteral with enum member inner types

- src/astUtils/reflection.ts
- src/astUtils/visitors.spec.ts
- src/lexer/TokenKind.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- src/parser/tests/statement/PrintStatement.spec.ts
`;` and `,` are converted to `PrintSeparatorExpression`
Addresses #1280
> Refactors PrintStatement so that `.values` array is all expressions

- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/types/VoidType.ts
- src/types/helpers.ts
Changes handling of `someVar = invalid` so that `someVar` is typed as `dynamic`
fixes #1383
> Assign invalid types as dynamic

- src/index.ts
Adds more exports to improve experience of using brighterscript from plugins. 
- add exports for a few missing brighterscript files
- add source-map convenience exports 
- broke named exports onto their own lines to improve diffing in the future
> Export more items

- src/files/BrsFile.Class.spec.ts
- src/parser/Statement.ts
When a child class extends a super class, but does not include its own `new` function, and the parent class has parameters, we are missing those parameters in the child class's factory.
> Fix class transpile issue with child class constructor not inherriting parent params

- src/files/BrsFile.spec.ts
- src/types/ReferenceType.ts
Fixes a crash related to BinaryReferenceType.
> Fix crash when unraveling complex BinaryReferenceType

- src/bscPlugin/hover/HoverProcessor.spec.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/files/BrsFile.spec.ts
- src/types/BscType.ts
- src/types/DoubleType.ts
- src/types/DynamicType.ts
- src/types/FloatType.ts
- src/types/IntegerType.ts
- src/types/LongIntegerType.ts
- src/types/ReferenceType.ts
- src/types/UnionType.ts
- src/util.spec.ts
- src/util.ts
New logic:
- the result of a binary op on unions depends on what types are in the union
- Basically, the "highest priority" type wins
- If two types are "equal priority", but not the same, treat it as Dynamic
-  `(float or integer) + (Integer) => Float`
- Treats "ObjectType" basically like "DynamicType"
> Fixes How BinaryOperators work on Unions

- src/ProgramBuilder.spec.ts
- src/ProgramBuilder.ts
Adds a flag to the `ProgramBuilder.run()` method that will enable/disable validation. This can be useful when trying to inspect various aspects of a project but you don't care about validation. Currently restricted to the `ProgramBuilder.run()` function but may be expanded to bsconfig and cli features in the future. It's also marked unstable because we have a specific purpose for this flag at the moment, all other behavior is undefined.
> Add `validate` flag to ProgramBuilder.run()

- src/Cache.ts
- src/CrossScopeValidator.ts
- src/DiagnosticFilterer.spec.ts
- src/DiagnosticFilterer.ts
- src/DiagnosticManager.spec.ts
- src/DiagnosticManager.ts
- src/Program.ts
- src/Scope.ts
- src/bscPlugin/CallExpressionInfo.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/files/BrsFile.ts
- src/files/XmlFile.spec.ts
- src/interfaces.ts
- src/types/BscType.ts
- src/util.ts
TBH, I'm not sure if this will speed up validation. However, there are many times in the validation process when the Diagnostic Manager needs to clear all diagnostics based on scope, file, tag, etc. Previously, this was done by looping all diagnostics, so if there are lots, it probably went slower and slower. This change should make it much more quick to find the diagnostics that need to be cleared.
Also added some more fine-grained Scope Validation metrics that are printed out with log-level debug:
```
[02:25:25:633 PM] [prj0] Validating scope components/search/SearchRow.xml
[02:25:25:634 PM] [prj0] Validating scope components/search/SearchRow.xml finished. (1.46ms)
[02:25:25:634 PM] [prj0] components/search/SearchRow.xml segment metrics:
[02:25:25:634 PM] [prj0]  - …
```
> Add lookup tables to DiagnosticsManager to speed up diagnostic clearing

- src/Program.ts
- src/Scope.ts
- src/astUtils/reflection.ts
- src/globalCallables.ts
- src/parser/AstNode.ts
- src/parser/Expression.ts
- src/parser/Statement.ts
- src/types/BooleanType.ts
- src/types/BscType.ts
- src/types/BuiltInInterfaceAdder.ts
- src/types/DoubleType.ts
- src/types/DynamicType.ts
- src/types/FloatType.ts
- src/types/FunctionType.ts
- src/types/IntegerType.ts
- src/types/LongIntegerType.ts
- src/types/ObjectType.ts
- src/types/StringType.ts
- src/types/VoidType.ts
- src/util.ts
- src/validators/ClassValidator.ts
Uses static instances for all native types.
Also adds some debug logging on build:
```
TYPES CREATED {
DynamicType: 1,
VoidType: 1,
StringType: 1,
IntegerType: 1,
InvalidType: 1,
UninitializedType: 1,
FunctionType: 1,
BooleanType: 1,
DoubleType: 1,
FloatType: 1,
LongIntegerType: 1,
ObjectType: 1,
ComponentType: 285,
TypedFunctionType: 50301,
ArrayType: 1704,
UnionType: 845,
AssociativeArrayType: 3206,
InterfaceType: 349,
ReferenceType: 10153,
ArrayDefaultTypeReferenceType: 40,
TypePropertyReferenceType: 1327,
ClassType: 48,
EnumMemberType: 138,
EnumType: 22,
BinaryOperatorReferenceType: 131,
ParamTypeFromValueReferenceType: 35,
NamespaceType: 80
}
TOTAL TYPES CREATED 68676
```
> Reduce BscType creation

- src/AstValidationSegmenter.ts
- src/DiagnosticManager.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
Adds debug log line like this:
```
Validation Walk Metrics (Scope: source): AssignmentStatement=12.321ms (1563), AstNode=2.899ms (1539), AugmentedAssignmentStatement=0.407ms (24), BinaryExpression=17.163ms (1767), CallExpression=30.524ms (3800), CallfuncExpression=0.060ms (2), DottedGetExpression=12.310ms (4191), DottedSetStatement=6.284ms (377), ForEachStatement=0.481ms (147), FunctionExpression=1.508ms (893), FunctionParameterExpression=10.127ms (1254), IncrementStatement=0.034ms (3), ReturnStatement=15.526ms (976), UnaryExpression=0.773ms (238), VariableExpression=24.405ms (10535)
```
Where for each kind of expression/statement validation, it says the total time and the number of times it was performed
Using this to try to figure out which kinds of expression validations are the worst …
> Scope validation part timing metrics

- package-lock.json
- package.json
- src/lsp/worker/WorkerPool.ts
- src/lsp/worker/WorkerThreadProject.ts
If you tried to use the brighterscript library in a worker_thread in any capacity, it would always try to run a new project on startup. But should only do that if we actually want to run the project itself via the language server. So added a runtime arg to further restrict when that code activates.
> Prevent running the lsp project in a worker thread

- src/astUtils/reflection.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/lexer/TokenKind.ts
- src/parser/Parser.spec.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
Makes the alias statement syntax used in v1 acceptable in v0, but then ignores it and doesn't do anything. It is empty in transpiles.
> Adds Alias statement syntax from v1 to v0

- src/files/BrsFile.spec.ts
- src/files/BrsFile.ts
Fixed a bug in `BrsFile.getClosestExpression()` that was returning the last expression in the AST when given an undefined position. Now we return `undefined` if the position or position.line is undefined, which should make more sense and also save a little processing time because we can exit early instead of traversing the entire AST tree
> Fixed getClosestExpression bug to return undefined when position not found

- src/Program.spec.ts
- src/Program.ts
- src/Scope.ts
Basic change was for all the data that was needed in later steps of the validation process is moved to the Program level, and only cleared once it's been used
> Fixes issue when cancelling an in-progress validation

- docs/classes.md
- docs/plugins.md
- scripts/compile-doc-examples.ts
- src/PluginInterface.ts
- src/Program.spec.ts
- src/bscPlugin/BscPlugin.ts
- src/examples/plugins/removePrint.ts
- src/interfaces.ts
- src/lsp/Project.ts
- src/util.spec.ts
- src/util.ts
Provide plugin factories with the bsc version. This will allow plugins to determine which features to support, or even load completely separate plugins for v0 and v1. 
Here are the docs on this feature: https://github.com/rokucommunity/brighterscript/blob/plugin-factory-version/docs/plugins.md#brighterscript-v1-compatability
Also fixed a small docs bug in classes.md (it came for free when updating the plugin docs)
> Support plugin factory detecting brighterscript version

- src/parser/Expression.ts
- src/parser/tests/expression/TemplateStringExpression.spec.ts
Fixes a few bugs in the template string transpiling that wasn't safely wrapping items in parentheses.
> More safely wrap expressions for template string transpile

- src/common/Sequencer.ts
Apparently the global `performance` object wasn't introduced until node 16. Let's import it from `perf_hooks` so we have less reasons to block backwards compatibility.
> Import `performance` from `perf_hooks` to work on node <16

- src/bscPlugin/validation/ScopeValidator.ts
Created [this ticket](https://github.com/rokucommunity/brighterscript/issues/1464) to number the issue.
Encountered a crash here when migrating to 1.0 due to some syntax that was okay in 0.69 but very not-okay in 1.0.
After I applied this hotfix locally, the errors displayed correctly in the Problems panel / build output, and I was able to fix the problematic syntax (and go back to using the published 1.0 release without this hotfix). 
Fix provided by @markwpearce
> Fix ScopeValidator crash

- src/CodeActionUtil.ts
- src/DiagnosticMessages.ts
- src/Program.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.spec.ts
- src/bscPlugin/codeActions/CodeActionsProcessor.ts
- src/bscPlugin/validation/BrsFileValidator.spec.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/files/BrsFile.spec.ts
void functions and subs may not have a return value. non-void functions and subs _must_ have a return value. This PR adds the following features:
> Flag incorrect return statements in functions and subs

- package.json
Removing unnesecary `npm ci` calls
> Remove `npm ci` from the `package` npm script since it's redundant

- scripts/scrape-roku-docs.ts
- src/roku-types/data.json
Adds missing `DialogBase` to the type system and fixed `standarddialog` and `dialog` to extend that instead of `group`. 
Also fixed a small crash in the docs scraper when certain arrays are missing.
> Add `DialogBase` to types

- src/parser/Expression.ts
- src/parser/tests/expression/NullCoalescenceExpression.spec.ts
- src/parser/tests/expression/TernaryExpression.spec.ts
Certain global functions are unable to be referenced as variables, and cause syntax errors on-device at compile time. Here's the list  of offending functions. 
```
'createobject',
'type',
'getglobalaa',
'box',
'run',
'eval',
'getlastruncompileerror',
'getlastrunruntimeerror',
'tab',
'pos'
```
These functions will now be excluded from scope capturing when transpiling ternary and null coalescing.
> Prevent runtime crash for non-referencable funcs in ternary and null coalescing

- src/CrossScopeValidator.spec.ts
- src/CrossScopeValidator.ts
Fixes a bug with component interface names not being recognized inside of typecasts, when accessing a property on that object, but only on first startup.
> Fix erraneous diagnostic for component name on first validation

- scripts/scrape-roku-docs.ts
- src/roku-types/data.json
Adds several missing contentNode fields.
- action
- priceDisplay
- price
- couponCode
- contentKey
- orderId
- drmParams
- 
Fixes #1471
> Add missing content node fields

- package-lock.json
- package.json
Adds a `bsc0` binary for allowing bsc v0 and v1 to exist simultaneously in node_modules, since the behavior is undefined right now which version of brighterscript would execute when running `bsc` on its own in that situation.
> Add `bsc0` cli binary name

- package-lock.json
- package.json
Adds a `bsc1` binary for coexistence with bsc v0 node modules.
> bsc1 cli binary

- src/DiagnosticManager.ts
- src/Program.spec.ts
- src/Program.ts
- src/astUtils/reflection.ts
- src/lsp/Project.spec.ts
- src/lsp/Project.ts
- src/lsp/ProjectManager.spec.ts
- src/testHelpers.spec.ts
Fixes #1487 by excluding diagnostics that don't have location. Also improves the situation by trying to attach diagnostics to other related locations if we couldn't find a valid location.
> Better diagnostic null location handling

- src/CrossScopeValidator.spec.ts
- src/CrossScopeValidator.ts
- src/DiagnosticMessages.ts
- src/Scope.spec.ts
- src/astUtils/reflection.ts
- src/bscPlugin/validation/ScopeValidator.spec.ts
- src/bscPlugin/validation/ScopeValidator.ts
- src/globalCallables.ts
- src/interfaces.ts
- src/parser/Expression.ts
- src/types/BscType.ts
- src/types/ComponentType.ts
- src/types/DynamicType.ts
- src/types/ReferenceType.ts
- src/types/TypedFunctionType.ts
- src/types/UnionType.spec.ts
- src/types/UnionType.ts
- src/types/helper.spec.ts
- src/types/helpers.ts
- src/util.ts
- Updates all BscTypes so they can potentially support CallFuncs. Will allow future work that will enable Interfaces to have Callfuncs (eg... `interface IMyComponent extends roSGNodeMyComponent` could bring in the callfuncs available in `roSGNodeMyComponent`)
- Particularly, support for checking a UnionType for callfuncs
- Extra work has been done to modify Diagnostic messaging so that if you try to use a function in a union, where the functions are incompatible, so it gives better messaging.
Examples:
Todo:
> Better Support for Union of Functions and CallFuncs

- docs/namespaces.md
Add some docs to explain how namespaces must be used with their underscore names for observefield
> Add some docs about ObserveField namespace caveats

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/lsp/ProjectManager.spec.ts
- src/lsp/ProjectManager.ts
There are issues with `bsconfig.json` auto-discovery:
- Language server may crash with large monorepos making use of symlinks; implementation uses `rokuDeploy.getFilePaths` which is quite inefficient for our need,
- `bsconfig.json` are looked into Search-excluded locations.
- replaces `rokuDeploy.getFilePaths` with a direct `fastGlob` call with `followSymbolicLinks` disabled,
- add Search `exclude` to the filters
Some users may rely on symlinks or search-hidden locations; this can be worked around by adding manually folders in the Workspace.
> Improve `bsconfig.json` auto-discovery

- src/lsp/ProjectManager.ts
Similarly to #1512 the language server is using `roku-deploy` to discover `manifest` files. This also causes issues.
This PR uses `fast-glob` directly.
Note: the discovery mechanism doesn't do any validation that the `manifest` files found are in fact Roku manifests. It is unsafe when the extension is used with non-Roku projects.
> Improve manifests discovery

- src/LanguageServer.spec.ts
- src/LanguageServer.ts
- src/bscPlugin/validation/BrsFileValidator.ts
- src/lsp/ProjectManager.spec.ts
- src/lsp/ProjectManager.ts
- src/testHelpers.spec.ts
- src/util.ts
The language server aggressively tries to discover Roku projects by default.
This is fine for Roku-only developers, and developers working in small to medium repositories.
This is causing issues for developers working on large codebases, like monorepos, and developers working on a lot of non-Roku projects, where the extension goes in the way. For instance in our monorepo, the language server goes out of memory while validating the projects, repeatedly as VS attempts to restart the server.
This PR adds an `enableDiscovery` lsp option, which defaults to `true` but can be disabled.
While adding the option, it turned out some refactoring had been done incorrectly; for instance `enableThreading` was never enabled due to incorrect workspace config preparation using unsafe casting.
Fixing the …
> Add `enableDiscovery` language server option

- src/lsp/ProjectManager.spec.ts
- src/lsp/ProjectManager.ts
Extension defaults `brightscript.projects` to an empty array - it really should be `undefined` but it shows that having an empty array in the settings stops discovery entirely.
> Fix discovery when `projects` is empty

- src/files/BrsFile.spec.ts
- src/types/UnionType.spec.ts
- src/types/UnionType.ts
Fixes #1488
If a union can be reduced to a primitive type, use that type for transpilation.
> Union Return type consistency
